### ISSUE TITLE
Can't find the saved PNG figure via glucifer!

### ISSUE THREAD

**Issue by wkillers** [underworldcode/underworld2#103] opened 2016-04-05 06:00 UTC
After I use glucifer to plot the figure, I used the savefig() method via "fig.save_image("xxx.png")" to save the figure into raster file, and the returning message looks like there is no error, but I can't find the saved PNG file anywhere.

**Comment by julesghub** [comment] 2016-04-05 06:37
We have found an issue - only on osx - that supports this behaviour. See https://github.com/OKaluza/LavaVu/issues/4 Can you reproduce the example in the first comment?

**Comment by OKaluza** [comment] 2016-04-05 07:31
Should be fixed by this workaround for bug in OS X GLUT f3c75c920778ba12f1e7abb1d64acfdfd00178fd

**Comment by wkillers** [comment] 2016-04-06 03:06
@OKaluza 

So do I have to modified the _glucifer.py my self and reconfiguring again?

**Comment by OKaluza** [comment] 2016-04-08 05:58
Hi @wkillers, you don't need to reconfigure, just get the updated version of _glucifer.py from the repo and it will take effect immediately, python scripts don't need to go through the configure/build process.

I can't duplicate the open_viewer issue, is this on Mac OSX? I'll have to test further.
Also not sure about the mpi4py issue, the mesh notebook works fine here.
Probably better to make separate issues for the other problems if they continue to occur.

If this has resolved the png file issue please go ahead and close this issue.

**Comment by wkillers** [comment] 2016-04-08 06:55
Hi @OKaluza, when I update the _glucifer.py from the repo and rerun the test, there are still some errors and the figure did't even show up, the error message are:
>  Sampling (8ZLIGTG1__dr) 100 x 100..100% (0) -- 0.009671 sec.
>     Transaction took 0.000009 seconds
>     160.012 kb of geometry data saved, 29.825 kb written.
>     Transaction took 0.000005 seconds
>     3.456 kb of geometry data saved, 0.618 kb written.
> Traceback (most recent call last):
>   File "01_GettingStarted.py", line 21, in <module>
>     fig.show()
>   File "../underworld2-master/glucifer/_glucifer.py", line 276, in show
>     return self._generate_image()
>   File "../underworld2-master/glucifer/_glucifer.py", line 435, in _generate_image
>     lavavu.execute(args)
> AttributeError: 'module' object has no attribute 'execute'

PS: I will put the open_viewer() and mpi4py problems into another issue.

**Comment by OKaluza** [comment] 2016-04-08 07:00
@wkillers yes you will now need to rerun swig and recompile since some other things have changed  since you last checked out the code apart from _glucifer.py

**Comment by wkillers** [comment] 2016-04-08 07:18
Hi @OKaluza , the problem still exists after I rerun swig and recompile, even I redo the reconfiguring it still appears, what I did is just download the updated _glucifer.py from the development branch and copy it to the directory glucifer/ to replace the old _glucifer.py and then do the following:cd ~/underworld2
$cd libunderworld
$./configure.py
$./scons.py
$cd libUnderworldPy
$./swigall.py
$cd ..
$./scons.py

My system is Mac OS X EI Capitan 10.11.4

**Comment by OKaluza** [comment] 2016-04-08 07:48
Sorry @wkillers, my mistake, things are in flux at the moment and your version of lavavu is too old to work with the fixed _glucifer.py
I suggest updating lavavu manually (the latest will still work with your older underworld version and the new _glucifer.py)

cd libUnderworld/gLucifer/Viewer
git pull
cd ../..

Then repeat build process from the ./scons.py step as you have above

**Comment by wkillers** [comment] 2016-04-08 08:01
Hi @OKaluza , when I run git pull under the directory libUnderworld/gLucifer/Viewer, it suggests that I am not currently on a branch:

> You are not currently on a branch.
> Please specify which branch you want to merge with.
> See git-pull(1) for details.
> 
>     git pull <remote> <branch>
> 
> SHANs-iMac:Viewer apple$ git pull 
> You are not currently on a branch.
> Please specify which branch you want to merge with.
> See git-pull(1) for details.
> 
>     git pull <remote> <branch>

**Comment by OKaluza** [comment] 2016-04-08 08:02
Try 
git pull origin master

**Comment by wkillers** [comment] 2016-04-08 08:10
Hi @OKaluza, after I run "git pull origin master" it looks like the lava has been updated successfully, and then repeat the build process from the ./scons.py step, and then I run the test it suggests another error:

> SHANs-iMac:my_underworld2 apple$ python 01_GettingStarted.py 
> Traceback (most recent call last):
>   File "01_GettingStarted.py", line 5, in <module>
>     import underworld as uw
>   File "../underworld2-master/underworld/__init__.py", line 44, in <module>
>     import libUnderworld
>   File "../underworld2-master/libUnderworld/__init__.py", line 1, in <module>
>     from libUnderworldPy import *
>   File "../underworld2-master/libUnderworld/libUnderworldPy/__init__.py", line 9, in <module>
>     import LavaVu
>   File "../underworld2-master/libUnderworld/libUnderworldPy/LavaVu.py", line 32, in <module>
>     _LavaVu = swig_import_helper()
>   File "../underworld2-master/libUnderworld/libUnderworldPy/LavaVu.py", line 28, in swig_import_helper
>     _mod = imp.load_module('_LavaVu', fp, pathname, description)
> ImportError: dlopen(../underworld2-master/libUnderworld/libUnderworldPy/_LavaVu.so, 10): Symbol not found: __Z10initVieweriPPc
>   Referenced from: ../underworld2-master/libUnderworld/libUnderworldPy/_LavaVu.so
>   Expected in: flat namespace
>  in ../underworld2-master/libUnderworld/libUnderworldPy/_LavaVu.so

**Comment by OKaluza** [comment] 2016-04-08 08:14
Oops, there's always one more thing, probably should have just suggested you to update to the dev branch, but we've come this far. This file from dev branch will need replacing too
https://github.com/underworldcode/underworld2/blob/development/libUnderworld/libUnderworldPy/LavaVu.i
Then re-do from swigall.py step

**Comment by wkillers** [comment] 2016-04-08 08:25
Thanks @OKaluza , this works!!! Finally we solve this problem, 

Thank you very much for your help since I am rather new to Python, and I will close this iuuse.

**Comment by wkillers** [comment] 2016-04-08 08:26
@

**Closed** 2016-04-08 08:28 UTC

**Comment by OKaluza** [comment] 2016-04-08 08:31
Woohoo! glad to hear it's working.
