### ISSUE TITLE
magnus build fail

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#219] opened 2017-05-08 02:14 UTC
Looks like h5py issues have come up on Magnus:

I tried to build using our official script:
https://github.com/underworldcode/underworld2/blob/development/docs/install_guides/pawsey_magnus.sh

Error:

```
Checking for package H5py... 
Attempting to build private h5py version at /scratch/m18/dsandiford/underworld2/h5py using cc=h5pcc. This may take a few minutes.
python setup.py configure -m --hdf5 /opt/cray/hdf5-parallel/1.8.13/GNU/48

Attempting to build private h5py version at /scratch/m18/dsandiford/underworld2/h5py using cc=gcc. This may take a few minutes.
python setup.py configure -m --hdf5 /opt/cray/hdf5-parallel/1.8.13/GNU/48
no

****  ERROR ****
Failed to locate required package H5py.
Details in 'config.log'
```

**Comment by dansand** [comment] 2017-05-08 02:22
'config.log' >>>
```
CONFIGURE H5PY
Checking if h5py in built in uw2 already, or provided by system (in that order of preference).
Attempting to import h5py...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: No module named h5py
h5py import failed.

No functional h5py found, lets try build our own using h5pcc.
Failed building h5py :(
Please check 'h5py_build.out' and 'h5py_build.err' in libUnderworld/h5py_ext
Still no functional h5py found, lets try build our own using uw2 CC.
Failed configuring h5py :(
Please check 'h5py_build.out' and 'h5py_build.err' in libUnderworld/h5py_ext

```

h5py_build.out >>

```

running configure
Autodetected HDF5 1.8.13
********************************************************************************
                       Summary of the h5py configuration

    Path to HDF5: '/opt/cray/hdf5-parallel/1.8.13/GNU/48'
    HDF5 Version: '1.8.13'
     MPI Enabled: True
Rebuild Required: True

********************************************************************************
```
h5py_build.err >>

```

Mon May  8 10:15:45 2017: [unset]:_pmi_alps_sync:alps response not OKAY
Mon May  8 10:15:45 2017: [unset]:_pmiu_daemon:_pmi_alps_sync failed
Mon May  8 10:15:45 2017: [PE_0]:_pmi_daemon_barrier:PE pipe read failed from daemon errno = Success
Mon May  8 10:15:45 2017: [PE_0]:_pmi_init:_pmi_daemon_barrier returned -1
```

**Comment by RebeccaFarrington** [comment] 2017-05-09 06:24
@dansand Have you had any luck with magnus?
I've managed to reproduce your problem, but not much else :/

@jmansour , do you have any ideas?

**Comment by rbeucher** [comment] 2017-05-10 04:17
Looks like It tries to build h5py with cc=gcc or h5pc. 

On a cray, the compilers are actually wrappers that do know about mpi, so sometimes configure scripts are a bit lost because they expect something like mpicc...

on a cray the compiler should be cc=cc

`cc=cc python setup.py configure -m --hdf5 /opt/cray/hdf5-parallel/1.8.14/GNU/48`

then

`cc=cc python setup.py build`

and it works....

**Comment by rbeucher** [comment] 2017-05-10 04:26
Well no it does not.. Just tried from scratch and I can not get it to compile again...

**Comment by rbeucher** [comment] 2017-05-10 05:04
`CC=cc` in fact... but even if it does compile, I get an error when trying to load it from python...

@jmansour ?

**Comment by jmansour** [comment] 2017-05-10 12:33
Ok, I believe the issue is due to multiple calls to MPI_Init.  

So, when we compile our own h5py, we import it a few times to test it is working correctly. However it seems on this machine MPI_Init can only be call once by any executable running under aprun, hence while the first test import is successful, any following ones will always fail.  I don't know why this worked previously, or what's changed.

In any case, i've update the build recipe.  Give it a crack (after updating your codebase as well), and let me know, .

**Comment by rbeucher** [comment] 2017-05-10 21:07
OK. I managed to compile the code. None of the tests passed though... partly because there is no runipy and partly because of that MPI_Init call issue (I guess?)

**Comment by jmansour** [comment] 2017-05-10 22:17
Yep, a bunch of tests are skipped because runipy is missing, but of the ones that can run, only the first one (docstest.py) passes, and then they all fail, most prob as you suggest due to the MPI_Init thing.  

This confirms that something has changed on their end.  We should message support, because being able to launch jobs sequentially within one session is often important, so guessing there should be a work around.

**Comment by jmansour** [comment] 2017-05-12 03:59
I've modified the test runner.  The default (test_basic.sh) still won't work, but if you use utils/run_test.py, you can now ask for 'aprun' to be prepended to the test run command.

**Comment by rbeucher** [comment] 2017-05-15 01:20
Thanks @jmansour. Can we close that one?

**Comment by RebeccaFarrington** [comment] 2017-05-16 01:06
@rbeucher , did you follow the install instructions?  I'm still having trouble getting h5py.

**Comment by RebeccaFarrington** [comment] 2017-05-16 02:06
sorry @rbeucher , I take it back!  All good here.  I'll close off this ticket :)

**Comment by lmoresi** [comment] 2017-05-19 12:03
I'm not sure about this ... I followed the instructions carefully and still had problems with hdf5 - it seems to build correctly but the configure breaks. A manual rebuild using Romain's recipe fixes the problem on subsequent configures. But this is not what the instructions say. 

The magnus environment is very different from a standalone PC and appears quite fragile. Anyone else having problems for a clean install ?

**Comment by jmansour** [comment] 2017-05-20 06:38
Heya @lmoresi.  I just gave this another crack with a completely fresh checkout.  It worked without any issues, so no idea why you're having problems.  

I assume you're on the dev branch?  Also, do you have anything in your bashrc that might be getting in the way? 

Post up your `config.log`, `h5py_ext/h5py_build.out` and `h5py_ext/h5py_build.err`

**Comment by lmoresi** [comment] 2017-05-20 10:15
Not sure - this was my first use of u/w on magnus and all profile / bashrc is default.

Since I did eventually succeed, I guess I will also need to nuke the build and start again to see if I can get the log files.

L


On 20 May 2017 at 4:38:37 pm, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

Heya @lmoresi<https://github.com/lmoresi>. I just gave this another crack with a completely fresh checkout. It worked without any issues, so no idea why you're having problems.

I assume you're on the dev branch? Also, do you have anything in your bashrc that might be getting in the way?

Post up your config.log, h5py_ext/h5py_build.out and h5py_ext/h5py_build.err

**Comment by lmoresi** [comment] 2017-05-20 10:55
Ah …


Attempting to build private h5py version at /home/lmoresi/+Underworld/underworld2/h5py using cc=gcc. This may take a few minutes.

no


****  ERROR ****

Failed to locate required package H5py.

Details in 'config.log'



***************************************

If you require help, send the files:

config.log

config.cfg (if it exists)

to: development@underworldproject.org

************************************



yes


There is quite a wait between the error message and the subsequent “yes”, and I think I killed it the first time and left everything in a mess from which I could not recover.

Perhaps we could add a note about that in the comments !!!

L


On 20 May 2017 at 4:38:37 pm, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

Heya @lmoresi<https://github.com/lmoresi>. I just gave this another crack with a completely fresh checkout. It worked without any issues, so no idea why you're having problems.

I assume you're on the dev branch? Also, do you have anything in your bashrc that might be getting in the way?

Post up your config.log, h5py_ext/h5py_build.out and h5py_ext/h5py_build.err

**Comment by jmansour** [comment] 2017-05-20 13:33
That's strange, I'm never seeing any error message.  ie, I get "yes" the first attempt.

**Comment by jmansour** [comment] 2017-05-20 13:35
Can you try without the "+" in the path? ie, something like `/home/lmoresi/Underworld/` instead of `/home/lmoresi/+Underworld/`.

**Comment by jmansour** [comment] 2017-05-21 01:35
So anyhow, went ahead and ran that experiment myself:

```bash
jmansour@magnus:~/+Underworld/libUnderworld> python configure.py --with-debugging=0 --with-graphics=0 --h5py-launch="aprun"
scons: Reading SConscript files ...
Checking whether the C compiler worksyes
Checking for Solvers... yes
Checking for package libm... yes
Checking for package libXML2... yes
Checking for package MPI... yes
Checking for package HDF5... yes
Checking for package Python... yes
Checking for package PETSc... yes
Checking for package Numpy... yes
Checking for package Mpi4py... yes
Checking for package H5py...
Attempting to build private h5py version at /home/jmansour/+Underworld/h5py using cc=gcc. This may take a few minutes.
yes

Saved configuration: "config.cfg"
  C compiler:     'gcc'
  C flags:        -O2 -g -Wall
  C preprocessor: ['HAVE_LIBM', 'HAVE_LIBXML2', 'HAVE_MPI', 'HAVE_HDF5', 'HAVE_PYTHON', 'HAVE_PETSC', 'HAVE_NUMPY', 'HAVE_MPI4PY', 'HAVE_H5PY', 'NDEBUG']
  Libraries: ['python2.7', 'hdf5', 'mpich', 'xml2', 'm', 'petsc']

*****************************************************************
* Successfully configured.                                      *
*                                                               *
* Note that basic usage metrics are dispatched when you use     *
* Underworld.                                                   *
* To opt out, set the UW_NO_USAGE_METRICS environment variable. *
* See PRIVACY.md for full details.                              *
*                                                               *
* Now run './compile.py' to build.                                *
*****************************************************************

scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.
jmansour@magnus:~/+Underworld/libUnderworld>
```

**Comment by rbeucher** [comment] 2017-05-25 06:08
Well It does compile but when importing I get:

```
Python 2.7.10 (default, Sep  6 2016, 10:44:23) 
[GCC 4.3.4 [gcc-4_3-branch revision 152973]] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import underworld
[Thu May 25 13:59:02 2017] [unknown] Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(483): 
MPID_Init(192).......: channel initialization failed
MPID_Init(569).......:  PMI2 init failed: 1 
```

**Comment by jmansour** [comment] 2017-05-25 07:15
You will need to run under aprun.  This *should* work

```bash
aprun python -c "import underworld"
```

**Comment by RebeccaFarrington** [comment] 2017-05-26 03:10
This worked for me - I can import underworld, also queued and successfully ran a convection test in parallel. 

I'm happy to close this issue...

**Comment by jmansour** [comment] 2017-05-26 03:19
Feel free to reopen as needed.

**Closed by jmansour** 2017-05-26 03:19 UTC
