### ISSUE TITLE
Permission denied when creating a file on docker

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#501] opened 2020-08-31 10:25 UTC
Hi all,

I just installed docker on my own desktop and then reload the image of UW2. I did not have an issue log in the UW2 interface with the following command:
docker run -p 8888:8888 -v ~:/workspace/user_data underworldcode/underworld2:2.7.1b

But I met the following issue when I tried to create a new ipynb file under user_data.

An error occurred while creating a new notebook: 
Permission denied: user_data/Untitled.ipynb

I thought this is because I do not have the right to write files into user_data in UW2 initially, but using the latest version of UW2 and the home directory of jovyan does not seem to help. 

docker run -p 8888:8888 -v ~:/home/jovyan/workspace underworldcode/underworld2:latest

Any suggestions please? Thanks a lot.

Best regards,
Ting

**Comment by jmansour** [comment] 2020-08-31 11:24
Is there a file `Untitled.ipynb` in your home directory?  Perhaps its permissions or ownership are getting in the way.

**Comment by tingyang2004** [comment] 2020-08-31 23:28
Thanks, John. There isn't a file named 'Untitled.ipynb' under the host machine directory. I cannot make a directory either.

**Comment by julesghub** [comment] 2020-08-31 23:51
Docker permissions are tricky. `2.7.1b` and `latest` docker images uses `jovyan` with a `$UID` of 1000.

What's your host machine user id:
  `echo $UID`  

If not 1000 then you'll have permission issues.

**Comment by tingyang2004** [comment] 2020-09-01 13:52
Thanks Julian. I will have a check of UID when I go back to the office.

**Comment by tingyang2004** [comment] 2020-09-06 08:59
echo $UID gives 1001.
So do I have to reassign UID of my desktop or may be I can sneak past it by some tricky commands in docker?

**Comment by lmoresi** [comment] 2020-09-06 10:52
Why don’t you try making the location where you are trying to run the docker read/write for all by way of a test. This is not the preferred solution but it would be useful to know if it helps.

L
On 6 Sep 2020, 6:59 PM +1000, tingyang2004 <notifications@github.com>, wrote:

echo $UID gives 1001.
So do I have to reassign UID of my desktop or may be I can sneak past it by some tricky commands in docker?

**Comment by tingyang2004** [comment] 2020-09-06 11:08
Make a directory readable and writable by anybody does solve the issue.

**Comment by julesghub** [comment] 2020-09-06 23:10
So the issue is jovyan (default user in the docker container) has UID 1001 and you user account has UID 1002. So you aren't the same users.
Making a location on your machine that is read+writable by everyone (or a group containing 1001 & 1002) is a solution if you're happy with it.

Otherwise we could add extra _fanciness_ to our docker to accept an input UID which could create that UID user to operate in the container. 
What do you think @jmansour, @lmoresi , @rbeucher?

**Comment by tingyang2004** [comment] 2020-09-07 12:04
I will make the directory read and writable by a group containing both 1000 and 1001 so that not everyone can get access to it. But I have to redo the above process every time I create a new directory. So it would be more helpful if there is a neater way to do that.

**Comment by julesghub** [comment] 2021-07-14 04:15
Closing ticket, reopen if you're still having problems with this.

**Closed by julesghub** 2021-07-14 04:15 UTC
