### ISSUE TITLE
Sticky air and velocity Field

### ISSUE THREAD

**Issue by AngelValverdePerez** [underworldcode/underworld2#145] opened 2016-06-06 12:24 UTC
I have some doubts with the sticky air (white layer of my image) and how uw2 manages this unreal layer. 
I have tried to include an sticky air layer but it gave me a lot of convergence troubles. 
Also, I do not know how could I have a free surface on the top wall of the domain. I think this could be the solution to the convergence problem. 

If anyone could give me a clue due to I'm new using this awesome code, I have another problem trying to set the velocity field. I want to do a compression model using two indentors. Is there anyway to move only the black blocks of the image? I don't know if the problem is because I define with the "fn.shape.Polygon" option

thank you very much for your time and experience

![slabimage_particle0000](https://cloud.githubusercontent.com/assets/18324577/15821800/5cfd421c-2bf2-11e6-9522-8f3d00263894.png)

**Comment by julesghub** [comment] 2016-06-10 04:39
Hi Angel,

Please see this user_guide https://github.com/underworldcode/underworld2/blob/master/docs/user_guide/06_Systems.ipynb
For an idea of how you can setup velocity conditions. 
1) Specify the value of the velocity on the individual nodes' degrees of freedom, eg velocityField.data[2] = [1.0,0.0] will set the velocity field on node 2 to be (vx,vy)=[1.0,0.0]. 
2) Flags the indices of the velocity mesh nodes to be dirichlet conditions, with one set of indices per component of the velocity field.

For an open surface boundary condition on the top wall you have to not flag any nodes from mesh.specialSets["MaxJ_VertexSet"] in the DirichletBoundary class.

You can use the same node index functionality to apply velocity conditions on the indentors.

J

**Comment by AngelValverdePerez** [comment] 2016-06-17 14:40
Thanks for the response, but the 2 option I don't get it, specific, I do not know how to apply to my script... I'm alone doing this here in Barcelona (Spain) and I got stuck.

I have tried this, is a llittle long but in # In[18]: I gave a velocity to my indentor, but is not working, I do not know why, :


# coding: utf-8

# In[1]:

import underworld as uw
import math
from underworld import function as fn
import glucifer
import numpy as np
import os


# In[2]:

xRes= 192
yRes = 64
dim  = 2
boxLength = 2.0
boxHeight = 0.6 

#Densidades
mantleDensity = 1.1786
CrustDensity  = 1.0 
CrustDensity2 = 1.0
astenosphereDensity=1.1786
pistonDensity  = 1.1786
airDensity = 3.5714e-4
#Viscosidades
airViscosity = 0.00001
MantleViscosity = 10.0
crustViscosity = 1.0
pistonViscosity = 1000.0
astenosphereViscosity = 0.1
#Factores de escala en el sistema internacional

lenght=500.0e3 
g=9.81 
densidad=2.8e3 
viscosidad=1e23
stress=densidad*g*lenght
tiempo=viscosidad/stress
velocidad=(lenght/tiempo)


outputPath = "./Cm5_1/"
if not os.path.exists(outputPath):
    os.makedirs(outputPath)


# In[3]:

mesh = uw.mesh.FeMesh_Cartesian( elementType = ("Q1/dQ0"),
                                 elementRes  = (xRes, yRes), 
                                 minCoord    = (0., 0.), 
                                 maxCoord    = (boxLength, boxHeight) ) 

#velocityField   = uw.mesh.MeshVariable( mesh=mesh,         nodeDofCount=dim )
velocityField1    = uw.mesh.MeshVariable( mesh=mesh, nodeDofCount=dim )
pressureField   = uw.mesh.MeshVariable( mesh=mesh.subMesh, nodeDofCount=1 )


# In[4]:

# initialise a swarm
swarm = uw.swarm.Swarm( mesh=mesh )

# add a data variable which will store information on the particle
materialVariable   = swarm.add_variable( dataType="int", count=1 )

# create a layout object that will populate the swarm across the whole domain
swarmLayout = uw.swarm.layouts.GlobalSpaceFillerLayout( swarm=swarm, particlesPerCell=15 )

# activate the layout object
swarm.populate_using_layout( layout=swarmLayout )


# In[5]:

surfaceSwarm = uw.swarm.Swarm( mesh=mesh )
ParPos= uw.swarm.Swarm ( mesh=mesh )
particle= np.zeros((10,2))
particle[0] = (0.0, 0.54)
particle[1] = (0.2, 0.54)
particle[2] = (0.4, 0.54)
particle[3] = (0.6, 0.54)
particle[4] = (0.8, 0.54)
particle[5] = (1., 0.54)
particle[6] = (1.2, 0.54)
particle[7] = (1.4, 0.54)
particle[8] = (1.6, 0.54)
particle[9] = (1.8, 0.54)

ParPos.add_particles_with_coordinates(particle)
'''print('x1 = {0:.2f}, y1 = {1:.2f},'.format(ParPos.particleCoordinates.data[0][0],ParPos.particleCoordinates.data[0][1]),  
     '''
       

# Control Particles

surfacePoints = np.zeros((2000,2))
surfacePoints[:,0] = np.linspace(0.0,2.0, 2000)
surfacePoints[:,1] = 0.54

surfaceSwarm.add_particles_with_coordinates( surfacePoints )


# In[6]:

# initialise the 'materialVariable' data to represent two different materials. 
MantleIndex = 0
astenosphereIndex = 1
CrustIndex = 2
Crust2Index = 3
PistonIndex = 4
airIndex= 5

# Initial material layout 
astenosphereY   = 0.34
airY = 0.54
airShape = np.array([ (0.0,0.6), (2.0,0.6), (2.0,0.54),(0.0,0.54) ])
crustShape = np.array([ (0.0,0.54 ), (2.0,0.54), (2.0,0.51), (0.0,0.51)])
crustShape2 = np.array([ (0.0,0.51), (2.0,0.51), (2.0,0.48), (0.0,0.48)])
mantleShape = np.array([(0.0,0.48), (2.0,0.48), (2.0,0.34), (0.0,0.34)])
pistonShape =np.array([(0.1,0.54),(0.16,0.54),(0.16,0.34),(0.1,0.34)])




# Le damos forma a los polígonos

crust = fn.shape.Polygon( crustShape )
crust2= fn.shape.Polygon( crustShape2 )
piston = fn.shape.Polygon( pistonShape )
mantle=fn.shape.Polygon(mantleShape)
air = fn.shape.Polygon( airShape )

# initialise everying to be upper mantle material
materialVariable.data[:] = MantleIndex


# change matieral index if the particle is in the lower mantle or slab shape
for particleID in range( swarm.particleCoordinates.data.shape[0] ):
    if swarm.particleCoordinates.data[particleID][1] > airY:
        materialVariable.data[particleID]     = airIndex   
    if swarm.particleCoordinates.data[particleID][1] < astenosphereY:
        materialVariable.data[particleID]     = astenosphereIndex      
    if  crust.evaluate(tuple(swarm.particleCoordinates.data[particleID])):
          materialVariable.data[particleID] = CrustIndex 
    if piston.evaluate(tuple(swarm.particleCoordinates.data[particleID])):
            materialVariable.data[particleID] = PistonIndex 
            
    elif crust2.evaluate(tuple(swarm.particleCoordinates.data[particleID])):
            materialVariable.data[particleID] = Crust2Index
   
   

figParticle = glucifer.Figure( figsize=(1000,600) )
figParticle.append( glucifer.objects.Points(surfaceSwarm, pointSize=2,colours="#440000:0.9 #440000:0.9", colourBar=False) )
figParticle.append( glucifer.objects.Points(swarm, materialVariable, pointSize=2, colours='brown red orange blue black white ') )
figParticle.show()


# In[7]:

# The yeilding of the upper slab is dependent on the strain rate.
strainRate_2ndInvariant = fn.tensor.second_invariant( 
                            fn.tensor.symmetric( 
                            velocityField1.fn_gradient ))
cohesion = 0.0022 #  30.215MPa
vonMises = cohesion / strainRate_2ndInvariant

alpha=3.03e-14   # 0.3 MPa/km ---> Ivone paper
misticparameter=1.0e-18
for index, coord in enumerate(mesh.data): 
    Byerlee = (cohesion+(alpha**coord[1])/(strainRate_2ndInvariant+misticparameter))


# The upper slab viscosity is the minimum of the 'slabViscosity' or the 'vonMises' 
crustYieldvisc = fn.exception.SafeMaths( fn.misc.min( Byerlee, crustViscosity) )
#mantleYieldvisc = fn.exception.SafeMaths( fn.misc.min(vonMises2, MantleViscosity) )
# Viscosity function for the materials 
viscosityMap = { 
                 MantleIndex      : MantleViscosity,
                astenosphereIndex : astenosphereViscosity,
                CrustIndex        : crustYieldvisc,
                Crust2Index       : crustViscosity,
                PistonIndex       : pistonViscosity,
                airIndex          : airViscosity,
                 }

viscosityMapFn = fn.branching.map( fn_key = materialVariable, mapping = viscosityMap )


# In[8]:

viscosityMap_init = {  
                      MantleIndex      : MantleViscosity,
                     astenosphereIndex : astenosphereViscosity,
                     CrustIndex        : crustViscosity,
                     Crust2Index       : crustViscosity,
                     PistonIndex       : pistonViscosity,
                     airIndex          : airViscosity,
                      }

viscosityMapFn_init = fn.branching.map( fn_key = materialVariable, mapping = viscosityMap_init )


# In[9]:

densityMap = {  
               MantleIndex      : mantleDensity,
              astenosphereIndex : astenosphereDensity,
              CrustIndex        : CrustDensity,
              Crust2Index       : CrustDensity,
              PistonIndex       : pistonDensity,
              airIndex          : airDensity,
               
               }

densityFn = fn.branching.map( fn_key = materialVariable, mapping = densityMap )

# Define our vertical unit vector using a python tuple
z_hat = ( 0.0, 1.0 )

# now create a buoyancy force vector
buoyancyFn = -1.0 * densityFn * z_hat


# In[10]:

pressureField.data[:] = 0.


# In[11]:

for index in mesh.specialSets["MinJ_VertexSet"]:
    velocityField1.data[index] = 0.0


# In[12]:

for index in mesh.specialSets["MaxJ_VertexSet"]:
        velocityField1.data[index] = 0.0


# In[13]:

mesh.data.shape


# In[14]:

velocityField1.data.shape

# In[15]:

for index in mesh.specialSets["MinI_VertexSet"]:
    velocityField1.data[index] = 0.0


# # ----------------

# In[16]:

for index in mesh.specialSets["MaxI_VertexSet"]:
        velocityField1.data[index] = 0.0



# In[17]:

#send boundary condition information to underworld
iWalls = mesh.specialSets["MinI_VertexSet"] + mesh.specialSets["MaxI_VertexSet"]
jWalls = mesh.specialSets["MinJ_VertexSet"] + mesh.specialSets["MaxJ_VertexSet"]
allWalls = iWalls + jWalls
freeslipBC = uw.conditions.DirichletCondition( variable      = velocityField1, 
                                               indexSetsPerDof = (iWalls,jWalls ) )




**#This is not working....
# In[18]:

for index, coord in enumerate(mesh.data):
    if coord[0] < 0.16 and coord[0] >= 0.09 and coord[1]<=0.54 and coord[1]>=0.34:
        velocityField1.data[index] = (0.43, 0.)**
    


# In[19]:

velSquared = uw.utils.Integral( fn.math.dot(velocityField1,velocityField1), mesh )
area = uw.utils.Integral( 1., mesh )
Vrms = math.sqrt( velSquared.evaluate()[0]/area.evaluate()[0] )


# In[20]:

propertyList = {"margin" : 70, "rulers" : True, "rulerticks" : 5 }  

figVelocityMag = glucifer.Figure(figsize=(1024,500), title="Velocidad", properties=propertyList )
figVelocityMag.append( glucifer.objects.VectorArrows( mesh, velocityField1, scaling=2, arrowHead=0.2, opacity=0.6 ) )
surf =  glucifer.objects.Surface(mesh, fn.math.dot(velocityField1,velocityField1)*velocidad*31536000000.0, logScale=False) 
surf.colourBar.properties={"ticks" : 4, "margin" : 450, "width" : 20, "tick1" : 1,"tick2":2, "tick3" : 3, "tick4":4, "align":'horizontal'}
surf.label("mm/year", (1.97,-0.2,0), scaling=0.1)
figVelocityMag.append(surf)
figVelocityMag.show()


# In[21]:

# Initial linear slab viscosity setup
stokesPIC = uw.systems.Stokes( velocityField = velocityField1,
                               pressureField = pressureField,
                               swarm         = swarm, 
                               conditions    = [freeslipBC,],
                               fn_viscosity   = viscosityMapFn_init, 
                               fn_bodyforce   = buoyancyFn )
# Create solver & solve
solver = uw.systems.Solver(stokesPIC)
solver.solve( nonLinearIterate=False ) 

# Change viscosityFN to non-linear upper slab viscosity version
stokesPIC.fn_viscosity = viscosityMapFn
# Re-solve
# use "lu" direct solve if running in serial or mg giving some acceleration
if(uw.nProcs()==1):
    solver.set_inner_method("mg") 
else: # use "mumps" parallel method
    solver.set_inner_method("mumps")
    
#solver.set_penalty(1.0e4)
solver.options.scr.ksp_rtol = 1.0e-4

solver.solve( nonLinearIterate=True )
solver.print_stats()


# In[22]:

advector = uw.systems.SwarmAdvector( swarm=swarm, velocityField=velocityField1, order=2 )
advector2       = uw.systems.SwarmAdvector( swarm=surfaceSwarm,     velocityField=velocityField1, order=2 )
advector3       = uw.systems.SwarmAdvector( swarm=ParPos, velocityField=velocityField1, order=2 )


# In[23]:

velSquared = uw.utils.Integral( fn.math.dot(velocityField1,velocityField1), mesh )
area = uw.utils.Integral( 1., mesh )
Vrms = math.sqrt( velSquared.evaluate()[0]/area.evaluate()[0] )


# In[24]:

propertyList = {"margin" : 70, "rulers" : True, "rulerticks" : 5 }  
figDensity = glucifer.Figure( figsize=(1024,500), title="Density", properties=propertyList)
surf= glucifer.objects.Points(swarm, densityFn*3.3e3, pointSize=4) 
surf.colourBar.properties={"ticks" : 4, "margin" : 450, "width" : 20, "tick1" : 1e3,"tick2":2e3, "tick3" : 3e3, "tick4":3.9e3, "align":'horizontal'}
surf.label("kg/m3", (2.01,-0.205,0), scaling=0.1)
figDensity.append(surf)
figDensity.show()


# In[25]:

propertyList = {"margin" : 70, "rulers" : True, "rulerticks" : 5 } 
figStrainRate = glucifer.Figure(figsize=(1024,500), title="Strain Rate", properties=propertyList)
surf = glucifer.objects.Surface(mesh, strainRate_2ndInvariant, logScale=True) 
surf.colourBar.properties={"ticks" : 4, "margin" : 450, "width" : 20, "tick1" : 0.003,"tick2":0.03, "tick3" :0.3, "tick4":5, "align":'horizontal'}
#surf.label("kg/m3", (2.01,-0.205,0), scaling=0.1)
figStrainRate.append(surf)
figStrainRate.show()


# In[26]:

propertyList = {"margin" : 70, "rulers" : True, "rulerticks" : 5 } 
figViscosity = glucifer.Figure(figsize=(1024,500), title="Viscosity", properties=propertyList)
surf = glucifer.objects.Points(swarm, viscosityMapFn*viscosidad, pointSize=4, logScale=True) 
surf.colourBar.properties={"ticks" : 4, "margin" : 450, "width" : 20, "tick1" : 1e18,"tick2":1e20, "tick3" :1e23, "tick4":1e26, "align":'horizontal'}
surf.label("Pa*s", (2.0,-0.205,0), scaling=0.1)
figViscosity.append(surf)
figViscosity.show()


# In[27]:

propertyList = {"margin" : 70, "rulers" : True, "rulerticks" : 5 }  
figStress = glucifer.Figure( figsize=(1024,500), title="Stress", properties=propertyList)
surf =  glucifer.objects.Points(swarm, (viscosityMapFn*strainRate_2ndInvariant)*stress/1e6, pointSize=4, logScale=True) 
surf.colourBar.properties={"ticks" : 4, "margin" : 450, "width" : 20, "tick1" : 1,"tick2":1e3, "tick3" :1e5, "tick4":4.2e7, "align":'horizontal'}
surf.label("MPa", (2.01,-0.206,0), scaling=0.1)
figStress.append(surf)
figStress.show()


# In[28]:

propertyList = {"margin" : 70, "rulers" : True, "rulerticks" : 5 }  
figVelocityMag = glucifer.Figure(figsize=(1024,500), title="Velocity", properties=propertyList)
figVelocityMag.append( glucifer.objects.VectorArrows(mesh, velocityField1, scaling=1.5, arrowHead=0.2) )
surf =  glucifer.objects.Surface(mesh, fn.math.dot(velocityField1,velocityField1)*velocidad*31536000000.0, logScale=False, valueRange=[0.,10.]) 
surf.colourBar.properties={"ticks" : 4, "margin" : 450, "width" : 20, "tick1" : 1,"tick2":2, "tick3" : 3, "tick4":4, "align":'horizontal'}
surf.label("mm/year", (1.97,-0.206,0), scaling=0.1)
figVelocityMag.append(surf)
figVelocityMag.show()


# In[31]:

'''velocity = velocityField1.evaluate(( 1.,0.54))[0,0]
print('vel = {0:.5e}'.format(velocity))'''


# In[32]:

steps = []
timeValues = []
particles = []
#strainRateValues  = []
#stressValues      = []
#velocityValues    = []
VrmsValues = []

time = 0.  # Initial time
step = 0   # Initial timestep
maxSteps = 50  # Maximum timesteps (201 is recommended)
steps_output = 1   # output every 10 timesteps
#datetime.datetime.now()
#now.strftime("%Y-%m-%d %H:%M")

while step < maxSteps:
    # Solve non linear Stokes system
    solver.solve(nonLinearIterate=True)
    # Retrieve the maximum possible timestep for the advection system.
    
    dt = advector.get_max_dt()
    #dt1=advector1.get_max_dt()
    # Advect using this timestep size
    advector.integrate(dt)
    advector2.integrate(dt)
    advector3.integrate(dt)
    #advector1.integrate(dt)
    # output figure to file at intervals = steps_output
    if step == 0 or step % steps_output == 0:
        ## this output path isn't working
        ## temporarily take these out till bug fix.
        figParticle.save_image(    outputPath + "particle"    + str(step).zfill(4))
        figVelocityMag.save_image( outputPath + "velocityMag" + str(step).zfill(4))
        figStrainRate.save_image(  outputPath + "strainRate"  + str(step).zfill(4))
        figViscosity.save_image(   outputPath + "viscosity"   + str(step).zfill(4))
        figStress.save_image(      outputPath + "stress"      + str(step).zfill(4))
        figDensity.save_image(     outputPath + "density"     + str(step).zfill(4))
    
    #strainRateCentral = strainRate_2ndInvariant.evaluate((1.,0.54))[0,0]
    #velocity = velocityField1.evaluate(( 1.0,0.54))[0,0]
    #devStressInvariantSquasher =  viscosityMap * strainRate_2ndInvariant.evaluate((1.0,0.3))[0,0]
    #x =  ParPos.particleCoordinates.data[5][0]
    #y = ParPos.particleCoordinates.data[5][1]
   
    #particles.append([x,y])
    #strainRateValues.append(strainRateCentral)
    #velocityValues.append(velocity)
    #stressValues.append(devStressInvariantSquasher)
    steps.append(step)
    timeValues.append(time)
    VrmsValues.append(Vrms)
    
    # Output time step, time, Vrms and CPUtime.  
    print( 'step = {0:6d}; time = {1:.3e}; x= {1:.5e}; y= {1:.5e} ; Vrms = {2:.3e}'.format(step,time,Vrms))
    
    # Increment time and timestep
    time += dt
    step += 1


# In[ ]:




# In[165]:

figParticle.show()


# In[166]:

stepArray=np.array(steps)
timeArray=np.array(timeValues)
#particleArray = np.array(particles)
#velArray      = np.array(velocityValues)
VrmsArray =np.array(VrmsValues)
#strainRateArray  = np.array(strainRateValues)
#devStressArray   = np.array(stressValues)

np.savetxt(outputPath+"/data.txt", np.c_[stepArray,timeArray, VrmsArray],fmt='%.4e', header="step     time      Vrms")


# In[167]:

get_ipython().magic(u'pinfo np.savetxt')

**Comment by AngelValverdePerez** [comment] 2016-06-17 15:41
Also I've tried with this:

velocityField1.data[5758:9091:101]=[0.043,0]
velocityField1.data[5759:9092:101]=[0.043,0]

but my indentor still do not moving ...

**Comment by AngelValverdePerez** [comment] 2016-06-17 15:56
The thing is that, when Uw solves the stockes problem, the velocity has changed, and all the particles are not moving or it is just moving the superior layer, but  that isn't what I want.
I would like to have a constant velocity for the indentor in every step, while the indentor is moving inside the layers. But there is no examples in the "guide", "example" or "develop" folders like the way I'm proposing

**Comment by julesghub** [comment] 2016-06-20 06:13
Hi Angel,

You must flag which velocity nodes you want the model to use as imposed (dirichlet) velocity conditions, ie. the indentors.
Similar to what is happening in ln[17] of your model. You are flagging the walls as imposed velocity conditions.

You will need something like the following for your indentors:

```
indentorSet = []   #empty set
for index, coord in enumerate(mesh.data):
   if coord[0] < 0.16 and coord[0] >= 0.09 and coord[1]<=0.54 and coord[1]>=0.34:
   velocityField1.data[index] = (0.43, 0.)
   indentorSet.append(index)   #build "imposed" set

# create FeMesh_IndexSet structure required for the imposing dirichlet conditions
indentorMeshSet = uw.mesh.FeMesh_IndexSet(mesh, topologicalIndex=0, size=len(indentorSet), fromObject=indentorSet )

# add the mesh index set to the original dirichlet conditions in ln[17]
newVC = uw.conditions.DirichletCondition( variable = velocityField1, indexSetsPerDof =(iWalls+indentorMeshSet,jWalls+indentorMeshSet ) )
```

Now pass `newVC` to the stokes system instead of `freeslipBC`

**Comment by lmoresi** [comment] 2016-06-20 16:07
Be careful that you do something so that there are no pressure degrees of freedom in a place where all velocity degrees of freedom are already specified.

Sent from my iPhone

On 19 Jun 2016, at 23:14, julesghub <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Angel,

You must flag which velocity nodes you want the model to use as imposed (dirichlet) velocity conditions, ie. the indentors.
Similar to what is happening in ln[17] of your model. You are flagging the walls as imposed velocity conditions.

You will need something like the following for your indentors:

indentorSet = []   #empty set
for index, coord in enumerate(mesh.data):
   if coord[0] < 0.16 and coord[0] >= 0.09 and coord[1]<=0.54 and coord[1]>=0.34:
   velocityField1.data[index] = (0.43, 0.)
   indentorSet.append(index)   #build "imposed" set

# create FeMesh_IndexSet structure required for the imposing dirichlet conditions
indentorMeshSet = uw.mesh.FeMesh_IndexSet(mesh, topologicalIndex=0, size=len(indentorSet), fromObject=indentorSet )

# add the mesh index set to the original dirichlet conditions in ln[17]
newVC = uw.conditions.DirichletCondition( variable = velocityField1, indexSetsPerDof =(iWalls+indentorMeshSet,jWalls+indentorMeshSet ) )


Now pass newVC to the stokes system instead of freeslipBC

**Comment by AngelValverdePerez** [comment] 2016-06-21 08:07
size=len(indentorSet) it was not working, so I change it : size=mesh.nodesGlobal. 

Does this solve the pressure degree of freedom?

Still is not converging. 

Is possible for underworld to create new particles for each loop if it is needed (boundary problems or convergence) instead of deforming the mesh?

**Comment by AngelValverdePerez** [comment] 2016-06-21 08:16
Now, before resolving the stokes problem, I can plot the velocityField, but when it is solve, appears a error message:

RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
SQL prepare error: (insert into geometry (object_id, timestep, rank, idx, type, data_type, size, count, width, minimum, maximum, dim_factor, units, minX, minY, minZ, maxX, maxY, maxZ, labels, data) values (2, 0, 0, 0, 2, 3, 1, 10000, 0, 0, inf, 1, '', 0, 0, 0, 0, 0, 0, ?, ?)) no such column: inf

**Comment by OKaluza** [comment] 2016-06-22 05:19
This error occurred during the visualisation step, when plotting a figure. 
A field has been queried for it's range (minimum, maximum) and it appears the maximum value returned is infinity. You could track down by elimination which field it is by commenting out the figure plotting except one at a time.

It shouldn't cause a crash so I'll check in a fix for that, but the root cause is elsewhere and presumably will cause other problems even if the vis issue is fixed.

**Comment by AngelValverdePerez** [comment] 2016-06-27 12:35
The script is not working.
This is what happening.
When the Stoke's problem is being solved, the only particles that move and evolve during time is inside the indenter, but the indenter still stay in the same place of the medium. 

Does anybody have or could lend me a script for tectonic compression, with a rigid block or not, due to reproduce the model in my computer? The aim in my work is to use UW2 instead of UW1 (We have an example for rigid block for UW1). 

The setup of this article is similar to what I'm trying to modelize: http://diapiro.ictja.csic.es/gt/ivone/docs/2014-Zlotnik_etal_Lithos2014.pdf

**Comment by RebeccaFarrington** [comment] 2016-06-29 02:51
Hi Angel,
Setting up a new model can be time consuming.  I've had a quick look at Sergio's model, it's really complex.  We don't have something similar in our examples.   I'd suggest when you're introducing new features into your model the initial attempts should be with the most simple model possible.  

As an example, can you get an indenter working with a uniform, isoviscous back ground material?

Let me know how you go.  I'm happy to spend some time looking into this with you, can you email me directly?

Do you mind if we close this issue?  It seems we've heading into a specific modelling problem, not a software/development issue.

Cheers,
Rebecca

**Comment by AngelValverdePerez** [comment] 2016-07-04 13:12
Yeah, better close this issue, I think you're right. Now it seems to be working, also I'd rather to keep in contact directly. 

Thank you everybody!

**Closed** 2016-07-04 13:12 UTC
