### ISSUE TITLE
Dockers and UW2 and Apple M1

### ISSUE THREAD

**Issue by drcoopa** [underworldcode/underworld2#589] opened 2021-11-13 01:29 UTC
Heya, I just update my operating system to Monterey (12.0.1) on a machine that's using a M1 chip.  I also updated Dockers to the M1 version and now I can no longer use jupyter notebooks.  As soon as I open a new notebook, I get this error in the terminal and the notebook window just spins and spins and spins doing nothing.

Error:  qemu: uncaught target signal 6 (Aborted) - core dumped

I do know that the Dockers update seemingly works as I do not get an error when I run hello world.  

Any ideas?

**Comment by lmoresi** [comment] 2021-11-14 09:29
Qn, dr C, Did you have the docker working under the M1 architecture and it broke when you upgraded the OS or is this the first go with M1 docker ? L Prof Louis ***@***.***(m) +61 4 0333 1413(us) +1 505 349 ***@***.***   From: drcoopa ***@***.***>Date: Saturday, 13 November 2021 at 12:29 pmTo: underworldcode/underworld2 ***@***.***>Cc: Subscribed ***@***.***>Subject: [underworldcode/underworld2] Dockers and UW2 and Apple M1 (Issue #589)Heya, I just update my operating system to Monterey (12.0.1) on a machine that's using a M1 chip. I also updated Dockers to the M1 version and now I can no longer use jupyter notebooks. As soon as I open a new notebook, I get this error in the terminal and the notebook window just spins and spins and spins doing nothing.Error: qemu: uncaught target signal 6 (Aborted) - core dumpedI do know that the Dockers update seemingly works as I do not get an error when I run hello world.Any ideas?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by drcoopa** [comment] 2021-11-14 19:33
It was working prior to the OS upgrade, albeit much slower than on other computers.  But Friday was my first try after the OS upgrade and that's when I started getting the errors.

**Comment by drcoopa** [comment] 2021-11-17 23:45
any suggestions?  I'd be sad to give up docker/jupyter notebooks...

**Comment by lmoresi** [comment] 2021-11-18 02:15
It should be super-fast as the M1 really is no slouch. @julesghub / @romain, is the docker that we distribute native on the arm architecture ?

**Comment by julesghub** [comment] 2021-11-18 05:46
Not sure - I haven't had the chance to test on an M1 yet. Is the mac at ANU accessible, last time (2weeks ago) I tried it wasn't.

**Comment by lmoresi** [comment] 2021-11-18 10:19
So I have been blocked by IT from installing this OS update. We'll have to get the test machine back online and upgraded. I think that machine should be ahead of the curve on upgrades for exactly these situations. 

We're working on it Katie, but it will take a bit of time because ANU is only just re-opening for physical access.

**Comment by drcoopa** [comment] 2021-11-18 17:49
Thanks, y'all!  Also, your IT is wise to block it - it's been a bit buggy to say the least.  Sorry to always be the one to find the really odd bugs.  And welcome back to physical access to your space!

**Comment by jmansour** [comment] 2021-11-19 10:32
All the UW docker images will be X86 so you must have been running under an emulation mode previously Katie (which also explains the lack of pace!).  Unfortunately, native ARM images are probably a while off still.  

Some relevant info here:

https://docs.docker.com/desktop/mac/apple-silicon/

In particular, they note that `qemu` isn't hugely robust with Docker containers. [sad face]

If you haven't already, I'd suggest removing all `underworld` related images, then try downloading/running them again. If that fails, you might try remove/reinstall Docker itself. You say UW containers/m1 worked previously, so that gives me some hope that it can work again!

But if X86 containers are truly broken for M1, then native build might be the only option, either bare metal or via containers, with the former probably being the path of least resistance (#540). The joys of the bleeding edge. 🙂

Actually, another option to get moving might be via cloud. I'm not sure what's the story with the Underworld cloud these days (@lmoresi ?), but I've used Deepnote before with success:

https://deepnote.com/

**Comment by drcoopa** [comment] 2021-11-19 22:47
just tried removing, uninstalling, reinstalling, etc. and alas, no such luck.  I've try the native build... and promise to never update my software ever again.  ;)

**Comment by jmansour** [comment] 2021-11-19 22:56
From #540 

https://www.underworldcode.org/articles/how-to-install-underworld-on-mac-osx-big-sur-apple-silicon-m1/

**Comment by drcoopa** [comment] 2021-12-30 00:00
well, I tried the native build, but for the life of me I can't get h5py to install.  I error out with "libhdf5.dylib' (no such file)".  It's perpetually looking in the wrong location for the library even though I've told it otherwise multiple times.  Any thoughts?  I feel pretty demoralized by this supposedly fast M1 chip.

**Comment by rbeucher** [comment] 2021-12-30 02:01
Hi @drcoopa 

I'm on leave until next week. There is an ARM64 docker image available on dickerhub but its not officially released. Happy to help next week if you can wait. 

Romain

**Comment by drcoopa** [comment] 2021-12-30 03:12
I can wait!  Thanks, Romain!  Happy New Year!🎆

**Comment by rbeucher** [comment] 2022-01-04 21:56
Hi @drcoopa 

So there is now an [ARM64](https://hub.docker.com/layers/underworldcode/underworld2/latest/images/sha256-41aed16485f36894cc7bb56dfb3150fbeced77fd653501d922f3cc50e7d83c8a?context=repo) docker image for Underworld2.

Note that this image is running UW 2.12. UWGeo has not been updated yet but I don't expect any major issue.

Please Install docker desktop for the M1. 
https://docs.docker.com/desktop/mac/apple-silicon/

Romain

**Comment by rbeucher** [comment] 2022-01-04 21:58
> well, I tried the native build, but for the life of me I can't get h5py to install. I error out with "libhdf5.dylib' (no such file)". It's perpetually looking in the wrong location for the library even though I've told it otherwise multiple times. Any thoughts? I feel pretty demoralized by this supposedly fast M1 chip.

Could you give me some details about what is going on? The things you have tried? I'd like to see if I can reproduce the pb.

**Comment by rbeucher** [comment] 2022-01-04 22:01
@lmoresi @drcoopa Note that this is for Big Sur... The Update to the new OS has been blocked by ANU.

I can't think of any reason why this should not work with the new OS though...

**Comment by lmoresi** [comment] 2022-01-04 22:04
I just did a native (homebrew-based) build for the uw software stack on big sur and I also found some complexity with missing libraries etc. I found it necessary to do a `pip3 install h5py --no-binary :all:` to force a recompile and eliminate a bunch of missing symbol errors.

I have put in a request for the new OS on my machine but these errors do feel more fundamental than that.

L

**Comment by drcoopa** [comment] 2022-01-04 22:32
yep, the issues were around supposedly missing libraries associated with h5py.  I'll try Louis' suggestion above and report out a detailed llist if I still get the same errors.  And I'll give the new docker image a whirl as well - yay!  and thank you!

**Comment by rbeucher** [comment] 2022-01-04 22:54
H5py is a pain... Forcing H5py to recompile is probably safer...

**Comment by rbeucher** [comment] 2022-01-04 23:00
@lmoresi I have updated the post... It doesn't hurt  to force a build.

**Comment by drcoopa** [comment] 2022-01-10 02:30
_Good news_ - docker image is working well!  yay!

_Better news_ - got a bit further in the H5py build.  I figured out why it wasn't finding the library.  There's a typo in the HDF5_DIR path in the instructions or it's at least different for me.  There was a "5" missing in the hdf portion.

From instructions: "HDF5_DIR=/opt/homebrew/Cellar/hdf/1.12.1"
Should be: "HDF5_DIR=/opt/homebrew/Cellar/hdf5/1.12.1"

_Bad news_ - I'm still erroring out in the H5py build.  This time it's clang errors.  Louis, did you run into those?

_Full error:_

error: command '/usr/bin/clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/cmcooper/uw2_virtualenv/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/t8/dx_vc3l90x16n8842k6xftf00000gp/T/pip-install-0y4iijn1/h5py_7b55254270e143489c685e3a12500438/setup.py'"'"'; __file__='"'"'/private/var/folders/t8/dx_vc3l90x16n8842k6xftf00000gp/T/pip-install-0y4iijn1/h5py_7b55254270e143489c685e3a12500438/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/t8/dx_vc3l90x16n8842k6xftf00000gp/T/pip-record-acpl3e9c/install-record.txt --single-version-externally-managed --compile --install-headers /Users/cmcooper/uw2_virtualenv/include/site/python3.9/h5py Check the logs for full command output.

**Comment by lmoresi** [comment] 2022-01-10 11:44
clang errors are the worst ... I looked up clang bugs  and found this which may be helpful:
https://youtu.be/5PWh3hA3KNc ? 

That might be clanger bugs ... but, it is about as helpful as anything else I can find.

**Comment by rbeucher** [comment] 2022-01-10 22:09
glad the docker images are working. I'll see if I can reproduce your issue with Clang.

**Comment by rbeucher** [comment] 2022-05-24 23:22
I am closing this now taht we have ARM docker images.

**Closed by rbeucher** 2022-05-24 23:22 UTC
Labels: docker
