### ISSUE TITLE
function evaluation blowing up

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#43] opened 2016-01-07 23:34 UTC
I'm computing the following integral, which seems to be working fine (i.e. returning reasonable values). But some way into the model run, the function blows up and kills the job. 

    vdint = uw.utils.Integral((4.*mantleviscosityFn*sinner)*rockIntVar, linearMesh)
    vdissfn.evaluate()[0]

RuntimeError: Value underflow error was encountered while evaluating function.

Will fn.exception.SafeMaths help here, or do I need to try and the root cause?

**Comment by julesghub** [comment] 2016-01-07 23:55
What's sinner?

Look for the root cause.
SafeMaths flags a numeric error in functions immediately, instead of
letting them propagate in the code.
You can safemath the functions used in the Integral(),
ie mantleviscosityFn, sinner, etc.... and that can help track which
function is blowing up.

**Comment by dansand** [comment] 2016-01-08 00:46
"sinner" is a function, the inner product of the second invariant of the
strain rate with itself (which I guess is redundant and could be replaced
by a multiplication ).

The problem is that the integral seems to work fine, up until a point where
it blows up. And that point also seems to change - i.e not always at the
same step.

Anyway, it's not a huge problem for the time being.

Cheers

On Fri, Jan 8, 2016 at 10:55 AM, julesghub <notifications@github.com> wrote:

> What's sinner?
>
> Look for the root cause.
> SafeMaths flags a numeric error in functions immediately, instead of
> letting them propagate in the code.
> You can safemath the functions used in the Integral(),
> ie mantleviscosityFn, sinner, etc.... and that can help track which
> function is blowing up.
>
> On 8 January 2016 at 10:34, Dan Sandiford <notifications@github.com>
> wrote:
>
> > I'm computing the following integral, which seems to be working fine (ie
> > returning reasonable values) But some way into the model run, the
> function
> > blows up and kills the job
> >
> > vdint = uwutilsIntegral((4*mantleviscosityFn*sinner)*rockIntVar,
> linearMesh)
> > vdissfnevaluate()[0]
> >
> > RuntimeError: Value underflow error was encountered while evaluating
> > function
> >
> > Will fnexceptionSafeMaths help here, or do I need to try and the root
> > cause?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/underworldcode/underworld2/issues/43>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/underworldcode/underworld2/issues/43#issuecomment-169844110>
> .
>



-- 
Dan Sandiford
PhD Candidate | Earth Sciences |  University of Melbourne
@sonderfjord | http://dansand.github.io/

Research Community Coordinator | Research Platform Services | University of
Melbourne
melbourne.resbaz.edu.au | @ResPlat | https://feb2016.resbaz.com/
--------------------------------------------------------------------------------------------
Research Platform Services:

--> We provide FREE training on 'next gen digi res skills'!
--> We consult with researchers on how to store+analyse their research data
problems.
--> We scale up your server rooms with add-on cloud, compute & high
performance computing.

Upcoming workshops: http://melbourne.resbaz.edu.au/swc-workshops
<http://melbourne.resbaz.edu.au/calendar>
---------------------------------------------------------------------------------------------

**Comment by jmansour** [comment] 2016-01-08 01:18
The exception that is raised here is raised by SafeMaths:

https://github.com/underworldcode/underworld2/blob/development/libUnderworld/Underworld/Function/src/Function.cpp#L40

You must be already are using it somewhere. But in any case, it is doing it's job.  Check the values of the  components of your function (mantleviscosityFn, sinner, rockIntVar).

**Comment by julesghub** [comment] 2016-01-13 05:25
@dansand what's the story? I'll close this, if still an issue please reopen

**Closed by julesghub** 2016-01-13 05:25 UTC

**Comment by dansand** [comment] 2016-01-13 05:46
Still trying to figure this one out. Maybe leave it open?
