### ISSUE TITLE
glucifer improvements

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#87] opened 2016-03-21 06:35 UTC
Few things we need added/exposed:

  *  contour plots - apparently in a previous version but hidden now.
  *  aspect ratios (ability to turn on/off)
  *  empty space between plot and title/legend (edit - optimize for min)
  *  example of how to make arrow heads preserve aspect ratio even if the box size is not 1:1
  *  editing of font, font size
  *  clipping of colour bar tick numbers if it is aligned to the right - hard to correct as spacing is not exposed
  *  simple way to plot swarm particles with a specific colour (without needing to plot by a variable name). Useful when plotting multiple swarms or a swarm over a vector field on a single figure.
  * Isobars & isosurfaces

Issues:

*    problem when you plot a vector field with v = 0 : result in radial lines to infinity. This is also a problem when (say) half the vector field = 0 in a 3D mesh.
*    special characters in title text, e.g. "=" was acting as an end of line marker
*    real time text labels; e.g. using the time of a model in the title of a figure that is saved to file each timestep

Enhancements:
*    Currently the interactive server side rendering option (accessed via the 'open_viewer' method), starts a server which publishes to localhost:someport. This is problematic for docker cloud usage, as we can't a priori know which ports will be available, and a static port is not an option as there will at times be multiple instances (for multiple users) running on the single machine. Is it possible instead to publish to some different address on the same port? Then perhaps each docker container would simply publish everything to port 80 perhaps, and then this would be mapped as necessary to different ports for each user.
*   It would be good to have an option to run the server side rendering inside an embedded window, ala the webgl viewer.

**Comment by garethkennedy** [comment] 2016-03-22 03:48
Few things we need added/exposed:
* contour plots - apparently in a previous version but hidden now.
* aspect ratios (ability to turn on/off)
* empty space between plot and title/legend (edit - optimize for min)
* example of how to make arrow heads preserve aspect ratio even if the box size is not 1:1
* editing of font, font size
* clipping of colour bar tick numbers if it is aligned to the right - hard to correct as spacing is not exposed
* simple way to plot swarm particles with a specific colour (without needing to plot by a variable name). Useful when plotting multiple swarms or a swarm over a vector field on a single figure.

Issues:
* problem when you plot a vector field with v = 0 : result in radial lines to infinity. This is also a problem when (say) half the vector field = 0 in a 3D mesh.
* special characters in title text, e.g. "=" was acting as an end of line marker

**Comment by lmoresi** [comment] 2016-03-22 03:54
Another problem I have found seems to be that gLucifer changes the cwd in a notebook to something deep inside the installation of python. Is that familiar to anyone else ?


On 22 March 2016 at 2:48:10 PM, Gareth Kennedy (notifications@github.com<mailto:notifications@github.com>) wrote:

Few things we need added/exposed:

  *   contour plots - apparently in a previous version but hidden now.
  *   aspect ratios (ability to turn on/off)
  *   empty space between plot and title/legend (edit - optimize for min)
  *   example of how to make arrow heads preserve aspect ratio even if the box size is not 1:1
  *   editing of font, font size
  *   clipping of colour bar tick numbers if it is aligned to the right - hard to correct as spacing is not exposed
  *   simple way to plot swarm particles with a specific colour (without needing to plot by a variable name). Useful when plotting multiple swarms or a swarm over a vector field on a single figure.

Issues:

  *   problem when you plot a vector field with v = 0 : result in radial lines to infinity. This is also a problem when (say) half the vector field = 0 in a 3D mesh.
  *   special characters in title text, e.g. "=" was acting as an end of line marker

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/87#issuecomment-199626443>

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

**Comment by OKaluza** [comment] 2016-04-08 09:04
Directory change was an OS X / GLUT bug that has been worked around so that's off the list for now. Regarding other items:
>   *  contour plots - apparently in a previous version but hidden now.
>   * Isobars & isosurfaces

Yes there is still no python interface for these, although you can do dynamic isosurfaces with the volume object. Problem was the old iso plots can sample on the mesh or globally and I was waiting for the mesh sampling capability to be enabled with functions as it is much faster than globally sampling. If this is not going to happen before the release I'll just implement the global versions.

>   *  editing of font, font size
>   *  clipping of colour bar tick numbers if it is aligned to the right - hard to correct as spacing is not exposed
>   *  simple way to plot swarm particles with a specific colour (without needing to plot by a variable name). Useful when plotting multiple swarms or a swarm over a vector field on a single figure.

Above features should already be there, if there are issues with using them I'll need examples to know where to look for the problem. Font support is never going to be word processor level though.

>   *  aspect ratios (ability to turn on/off)
>   *  empty space between plot and title/legend (edit - optimize for min)
>   *  example of how to make arrow heads preserve aspect ratio even if the box size is not 1:1
> Issues:
> *    problem when you plot a vector field with v = 0 : result in radial lines to infinity. This is also a problem when (say) half the vector field = 0 in a 3D mesh.
> *    special characters in title text, e.g. "=" was acting as an end of line marker
> *    real time text labels; e.g. using the time of a model in the title of a figure that is saved to file each timestep

Will definitely need examples here to understand, perhaps we could start a notebook demonstrating all known vis issues that I can work through?

**Comment by RebeccaFarrington** [comment] 2016-04-11 02:48
@garethkennedy - were you able to start the notebook @OKaluza suggests?

**Comment by lmoresi** [comment] 2016-04-11 02:55
One other thing to clarify in the example notebooks is how to use the properties dictionary which is a universal argument in all the gLucifer functions.

I had to read through the source code to figure it out and even then was not sure if I had it all correct.

/for changing font sizes etc, it would be useful to have a comprehensive guide in the notebooks. Gareth / Owen perhaps to work on this collectively.

L

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>


On April 10, 2016 at 7:48:47 PM, RebeccaFarrington (notifications@github.com<mailto:notifications@github.com>) wrote:

@garethkennedy<https://github.com/garethkennedy> - were you able to start the notebook @OKaluza<https://github.com/OKaluza> suggests?

**Comment by garethkennedy** [comment] 2016-04-21 05:35
A lot of the issues above have been addressed by the look of it.

For those outstanding, I've added some general issue/list of desire notebooks in
docs/development/gLuciferIssues.ipynb
docs/development/gLuciferPubQuality.ipynb

**Comment by garethkennedy** [comment] 2016-04-28 01:32
@OKaluza have you had a chance to look at the dev notebooks? The issues one has just been updated re parallel friendly fig.show command in example 4.

**Comment by OKaluza** [comment] 2016-04-29 04:15
@garethkennedy thanks for these, checking it out today

**Comment by garethkennedy** [comment] 2016-05-17 06:17
@OKaluza there looks to be an issue with fig.show() and fig.saveimage() in parallel. Specifically at the "Sampling (blah) 100 * 100 ..." step. Often this never finishes when it should take 0.01 s. It is quite intermittent re when it works or now.

I've attached an example python script here which I ran locally using mpirun -np 4...
The gLuc one has this issue on my laptop (ubuntu 14.04) but the other file which just has the fig.show() commands commented out runs fine.

Any thoughts? Something that has changed recently?

[figshowIssue.tar.gz](https://github.com/underworldcode/underworld2/files/267500/figshowIssue.tar.gz)

**Comment by OKaluza** [comment] 2016-05-18 04:13
@garethkennedy fixed with bcee0d8932491b84986eccc792bd42697e436905 this was a weird one, thanks for the comprehensive bug report.

**Comment by julesghub** [comment] 2016-05-24 03:11
@OKaluza i just tried this on the latest code and I couldn't see the mesh in ipynb nor in the standalone viewer. If I change the min/max coords to be 0,0,0 & 1,1,1 it works. 
```
import underworld as uw
import glucifer

mesh = uw.mesh.FeMesh_Cartesian( elementType='Q1/dQ0', elementRes=(10,5,10), minCoord=(0,0,0), maxCoord=(10,5,10) )

fig = glucifer.Figure()
fig.append( glucifer.objects.Mesh(mesh))
fig.show()
```

bug re: clipping plane perhaps?

**Comment by julesghub** [comment] 2016-05-27 00:36
@OKaluza  i just tried fig.show("webgl") on a recent build and it failed with:
![screenshot from 2016-05-26 14 50 53](https://cloud.githubusercontent.com/assets/13825704/15564047/667d089e-2351-11e6-927c-3f618407b81d.png)

**Comment by garethkennedy** [comment] 2016-05-27 03:57
Sorry @OKaluza another one for you regarding fig.show()

I just tested one of the examples in parallel on Raijin (1_05_StokesSinker.py).
It crashed at the first fig.show() with the following error:

=====================================================================================
Error running Underworld - Signal 15 'SIGTERM' (Termination Request).
This is caused by an external call to terminate the code.
This could have happened by a queueing system (e.g. if the code has run longer than allowed),
the code might have been killed on another processor or it may have been killed by the user.
[r96:17743] 3 more processes have sent help message help-mpi-runtime.txt / mpi_init:warn-fork
[r96:17743] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[gfk563@raijin2 examples]$ cat raijing-run.sh.e6530038
In func open: Function XOpenDisplay(NULL) returned NULL
In func open: Function XOpenDisplay(localhost:0.0) didn't work.
In func open: Function XOpenDisplay(":0.0") returned NULL
IBO creation failed!

Traceback (most recent call last):
  File "1_05_StokesSinker.py", line 188, in <module>
    fig1.show()
  File "/home/563/gfk563/underworld2/glucifer/_glucifer.py", line 504, in show
    lavavu.execute(args)
RuntimeError: IBO creation failed!

**Comment by jmansour** [comment] 2016-05-27 04:05
I know Owen's been looking at Raijin a bit recently with Catherine so he
might have an easy fix, but otherwise I suggest we don't bother supporting
image rendering on big machines any longer at all.

I'd rather people start testing out the viz *store* workflows, and it's a
better use of Owen's time developing these approaches rather than debugging
on big machines.  And it's much more useful for 3d simulations anyhow,
which is what people are likely to be running.

**Comment by garethkennedy** [comment] 2016-05-27 04:07
Are there any examples for using viz *store*? Is everything exposed in the python layer yet?

**Comment by OKaluza** [comment] 2016-05-27 04:20
I appreciate the reports, but having a single ongoing issue that will never be closed is not the way to do this, the original post already had far too many issues for a single post and it's now catch-all for vis related bugs. No more issues here please, it's not hard to create a new one. If multiple vis issues on the underworld2 tracker is not desired, add it to the LavaVu on instead https://github.com/okaluza/lavavu/issues /rant

@julesghub looking at webgl output issues now.

@garethkennedy @jmansour  raijin just doesn't have graphics capability, you can set with-graphics=0 when configuring to avoid getting these errors. Unless the admins install an up to date Mesa graphics stack this will always fail.

I'm about to check in another iteration of the store workflow which should make things easier to use on clusters without graphics. There will be an examples, I can modify the raytay and/or subduction examples or create a new notebook along similar lines.

**Comment by jmansour** [comment] 2016-05-27 04:27
I agree, the catch all ticket isn't the way forward.  Issues get lost. People can/should open specific tickets.  

I'm going to close this, and suggest that it get's review for specific items that require addressing, with new tickets created for those.

**Closed by jmansour** 2016-05-27 04:27 UTC

**Comment by OKaluza** [comment] 2016-05-27 04:35
Cheers John!

**Comment by lmoresi** [comment] 2016-05-27 04:45
Sounds like a quality day task !

Sent from my iPhone

On 26 May 2016, at 21:27, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:


I agree, the catch all ticket isn't the way forward. Issues get lost. People can/should open specific tickets.

I'm going to close this, and suggest that it get's review for specific items that require addressing, with new tickets created for those.
