### ISSUE TITLE
slower pressure iteration convergence rate for more cores

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#385] opened 2019-05-27 00:46 UTC
Hi all,

I am running a slab subduction model with a model resolution of 1210x202. Periodic boundary condition is applied for the side boundaries (a snapshot of model evolution is as below). 
When I use 24 cores, that is, around 101x101 elements in each core, it cost me around 50 min to finish the first 30 steps. Since I am planning to run the model for over 10 thousand steps, I tried to increase the core number to speed up the model. However, when I use 48 cores, that is, around 76x68 elements in each core, it cost me around 46 min to finish the first 30 steps, less than 10% faster than 24 cores. When I use 96 cores, around 51x51 elements in each core, it cost me even around 80 min to finish the first 30 steps.
I am wondering what is causing the slower convergence rate increasing the number of cores to 96? Is it communication between different nodes? Any suggestion I can speed up the model? A part of the stokes solver information is demonstrated below, you can see that pressure iteration gets much slower when I use more cores:
24 Cores:
![24Cores](https://user-images.githubusercontent.com/26615840/58389305-045c1180-805c-11e9-9531-194343b4122e.png)

48 Cores:
![48Cores](https://user-images.githubusercontent.com/26615840/58389307-0aea8900-805c-11e9-9a17-3be6005b19c5.png)

96 Cores:
![96Cores](https://user-images.githubusercontent.com/26615840/58389308-0f16a680-805c-11e9-91d4-dbca3cd63117.png)

Thanks a lot and let me know if you need more information.
Ting

**Comment by julesghub** [comment] 2019-05-27 05:42
Yes the communication between nodes is the problem. 
The model is over decomposed and the communication overhead is significant relative to the compute (individual CPU) work. That's why time goes up the more CPUs you use. 

Unfortunately it is difficult to give you a good "rule of thumb" to get it right for CPU work vs parallel decomposition. It depends on the model, solver setup and hardware platform. 
For a 1210x202 model i would guess around 4-12 procs would be good.

**Comment by tingyang2004** [comment] 2019-05-27 06:43
Thanks, Julian.
Hmmm, that is strange. In rifting models I have tried before (also with very complex and non-linear rheology), 20x20 elements per CPU can be much faster than 50x50 elements. I am wondering why 50x50 elements per CPU is much slower than 100x100 elements per CPU in this case.

**Comment by rcarluccio** [comment] 2019-05-27 06:54
what usually works with me for A subduction model is the following:

32^3= 32768 number of cells —>1-2 (prescribed) to 8 cpu. 2cpu


1210*210 /32768  -----> 8 to 16 cpus.


Increasing the numbers of cores not necessarily increases your performance,
of course it also depends by your model complexity and so on.

**Comment by tingyang2004** [comment] 2019-05-27 07:29
Thanks, Roberta,

I have reduced the model size to 605x129 elements.
Two number of cores are investigated for the same script.
For 24 cores, that is, 51x65 elements in each core, it takes around 9 min to finish the first 10 steps.
For 12 cores, that is, 101x65 elements per core, it takes around 18 min to finish the first 10 steps.
One possible explanation is that with the increasing number of elements, the preferred number of elements per core also increases.

**Comment by jmansour** [comment] 2019-05-27 11:15
Ting I'm not sure what solver setup you're using, but MG will generally be
optimal when you choose resolutions which are powers of 2.  And you should
avoid primes.  So instead of 604x129, you should use perhaps 512x128.

You might also consider using MUMPS.

**Comment by tingyang2004** [comment] 2019-05-27 11:44
Thanks John. MUMPS is used for the stokes solver, so the power of 2 rule is not needed. I guess MG is still much less efficient than MUMPS in 2D models? Not sure what you mean by prime.

**Comment by jmansour** [comment] 2019-05-27 23:41
Prime numbers, which are the worst for MG.  In any case, I believe you are correct that it shouldn't matter for MUMPS.   

I would suggest then you do also try MG for comparison.

**Comment by tingyang2004** [comment] 2019-05-28 01:06
Thanks, I'll have another try and see MG is more efficient than MUMPS for this case.

**Comment by tingyang2004** [comment] 2019-06-19 04:33
Well, my recent tests for 3D subduction models (264x96x64 elements) do suggest that 32x32x32 elements per core does the most parallel efficiency. On the other hand, for 2D subduction models, 50x50 to 100x100 elements per core does the most parallel efficiency depending on different mesh resolutions.
Will close it since the doubts have been clarified now.

**Comment by rcarluccio** [comment] 2019-06-19 04:48
What is approx your total BSSCR Linear solve time per time step and how
many non-linear iterations do you usually need for a 264x96x64 elements
model?

**Comment by tingyang2004** [comment] 2019-06-19 06:34
It takes around 15 non-linear iterations to get converged for the 0th step, and 1-2 non-linear iterations to get converged for the following steps, similar to 2D cases. But each non-linear iteration is pretty slow, it costs around 10 min with 32x32x32 elements per core, so around 20 min for each time step. The first step of the model used is attached below showing the rheology (diffusion, dislocation, yielding) used. It would be very helpful if the convergence rate can be accelerated a bit.

![SlabSubduction3D2AStep0](https://user-images.githubusercontent.com/26615840/59741771-84ae1500-929e-11e9-8ec8-6617b0fdbdd2.png)

**Comment by arijitlaik** [comment] 2019-06-19 06:55
Hi @tingyang2004, thanks a lot for guiding with the timing and procs counts, could you let us know what is the non-linear solver tolerance that your are using?

**Comment by tingyang2004** [comment] 2019-06-19 07:10
solver.options.scr.ksp_rtol=1.0e-6 for the linear iteration
and solver.solve(nonLinearIterate=True,nonLinearTolerance=0.01) for nonlinear iteration, if that helps. @arijitlaik

**Comment by arijitlaik** [comment] 2019-06-19 07:52
thanks :)

**Comment by jmansour** [comment] 2019-06-19 22:01
@tingyang2004 are these results for MUMPS? Did you end up trying MG for comparison?

**Comment by tingyang2004** [comment] 2019-06-19 23:29
All 3D models use mg.
One interesting finding is that 33x32x32 elements per cpu can be several times faster than 32x32x32 elements per cpu. maybe due to the interaction between the complex rheology and mesh resolution.

**Comment by jmansour** [comment] 2019-06-19 23:32
Really?  That is indeed 'interesting'. 🤨

**Comment by tingyang2004** [comment] 2019-06-20 00:56
Another interesting thing is that, for a 256x96x64 model, it takes around 40 min for each step with 48 cores, i.e., 32^3 elements per core. When I double the number of cores to 96 or even to 192, the convergence rate is getting slower. However, when I double the number of cores again to 384, it takes around 4 min for each step, or around 10 times faster than 48 cores. Seems a lot of bizarre things there.

**Comment by jmansour** [comment] 2019-06-20 01:03
That is very strange @tingyang2004.  Might be worth also checking how repeatable those timings are.

**Comment by julesghub** [comment] 2019-06-20 01:04
What machine are you running on? Are the hardware architecture details available?

**Comment by tingyang2004** [comment] 2019-06-20 01:16
Below is the first paragraph from the User's Manual @julesghub @jmansour 
Will check the performance again later today.

“TaiYi” is a supercomputer based on Intel Xeon Gold processors from the Skylake generation. It is a 
Lenovo system composed of SD530 Compute Racks, an Intel Omni-Path high performance network interconnect and running RedHat Linux Enterprise Server as operating system. Its current Linpack Rmax 
Performance is 1.67 Petafops

**Comment by rcarluccio** [comment] 2019-06-20 07:05
Hi Ting,

Would you mind sharing a screen shot of your velocity field at the first
step? I'm just curious to look at how it looks like. I'll start running my
3d models again next week and then we can compare results. What are the
size of model domain (coords)?

**Comment by tingyang2004** [comment] 2019-06-20 07:26
The velocity field shown above is for the first (0th) time step although I did not scale it with velocity magnitude and so only direction information is meaningful. The domain size is 1500 km deep x 3000 km long x 1500 km half wide.

**Comment by tingyang2004** [comment] 2019-06-20 07:27
And am happy to compre the results with you. @rcarluccio

**Comment by rcarluccio** [comment] 2019-06-20 07:32
did you send another screenshot? I can only visualise this
https://user-images.githubusercontent.com/26615840/59741771-84ae1500-929e-11e9-8ec8-6617b0fdbdd2.png
. Thanks for the info I'll reproduce something similar.

**Comment by tingyang2004** [comment] 2019-06-20 07:38
No, this is what I meant.

**Comment by tingyang2004** [comment] 2019-06-20 07:39
Note that I have skipped the subduction initiation period, as always.

**Comment by tingyang2004** [comment] 2019-06-22 03:25
For the issue that 33x32x32 elements per cpu is one time faster than 32x32x32 elements per cpu. I have checked the log file today. It looks like the pressure solver is one time slower for 32^3 CPUs. 
33x32x32 model:

Non linear solver - iteration 14
Linear solver (XQ96L7RB__system-execute)

  [1] SROpGenerator_SimpleCoarserLevel: time = 1.83635e-02
  Setting schur_pc to "gkgdiag"


SCR Solver Summary:

  Multigrid setup:        = 0.242 secs
  RHS V Solve:            = 6.193 secs / 18 its
  Pressure Solve:         = 212.4 secs / 48 its
  Final V Solve:          = 5.804 secs / 20 its

  Total BSSCR Linear solve time: 236.770290 seconds

Linear solver (XQ96L7RB__system-execute), solution time 2.369147e+02 (secs)
In func SystemLinearEquations_NonLinearExecute: Iteration 14 of 500 - Residual 0.0080322 - Tolerance = 0.01
Non linear solver - Residual 8.03220671e-03; Tolerance 1.0000e-02 - Converged - 4.615428e+03 (secs)

In func SystemLinearEquations_NonLinearExecute: Converged after 14 iterations.
^[[1;35m

Pressure iterations:  48
Velocity iterations:  18 (presolve)
Velocity iterations: 755 (pressure solve)
Velocity iterations:  20 (backsolve)
Velocity iterations: 793 (total solve)

SCR RHS  setup time: 1.1543e+01
SCR RHS  solve time: 6.1928e+00
Pressure setup time: 6.2304e-03
Pressure solve time: 2.1236e+02
Velocity setup time: 9.5367e-07 (backsolve)
Velocity solve time: 5.8037e+00 (backsolve)
Total solve time   : 2.3677e+02

Velocity solution min/max: 0.0000e+00/0.0000e+00
Pressure solution min/max: 0.0000e+00/0.0000e+00

^[[00m
('hgn 12: ', datetime.datetime(2019, 6, 19, 19, 17, 31, 464663))
step =      0; time = 0.00000e+00; time_Myr = 0.00000e+00

32x32x32 model:

Non linear solver - iteration 14
Linear solver (DJ25GQCN__system-execute)

BSSCR -- Block Stokes Schur Compliment Reduction Solver
AUGMENTED LAGRANGIAN K2 METHOD - Penalty = 0.000000

SROpGenerator_SimpleFinestLevel: time = 2.39016e-01
  [4] SROpGenerator_SimpleCoarserLevel: time = 4.37264e-02
  [3] SROpGenerator_SimpleCoarserLevel: time = 1.78812e-02
  [2] SROpGenerator_SimpleCoarserLevel: time = 1.48602e-02
  [1] SROpGenerator_SimpleCoarserLevel: time = 1.41797e-02
  Setting schur_pc to "gkgdiag"


SCR Solver Summary:

  Multigrid setup:        = 0.3395 secs
  RHS V Solve:            = 17.6 secs / 20 its
  Pressure Solve:         = 640.1 secs / 47 its
  Final V Solve:          = 16.97 secs / 20 its

  Total BSSCR Linear solve time: 679.924037 seconds

Linear solver (DJ25GQCN__system-execute), solution time 6.800786e+02 (secs)
In func SystemLinearEquations_NonLinearExecute: Iteration 14 of 500 - Residual 0.0083099 - Tolerance = 0.01
Non linear solver - Residual 8.30994138e-03; Tolerance 1.0000e-02 - Converged - 9.481746e+03 (secs)

In func SystemLinearEquations_NonLinearExecute: Converged after 14 iterations.
^[[1;35m

Pressure iterations:  47
Velocity iterations:  20 (presolve)
Velocity iterations: 747 (pressure solve)
Velocity iterations:  20 (backsolve)
Velocity iterations: 787 (total solve)

SCR RHS  setup time: 4.3717e+00
SCR RHS  solve time: 1.7601e+01
Pressure setup time: 6.0389e-03
Pressure solve time: 6.4010e+02
Velocity setup time: 7.1526e-07 (backsolve)
Velocity solve time: 1.6970e+01 (backsolve)
Total solve time   : 6.7992e+02

Velocity solution min/max: 0.0000e+00/0.0000e+00
Pressure solution min/max: 0.0000e+00/0.0000e+00

^[[00m
('hgn 12: ', datetime.datetime(2019, 6, 19, 15, 59, 3, 87266))
step =      0; time = 0.00000e+00; time_Myr = 0.00000e+00


I have attached the model viscosity and velocity solution at 0_th step for these two models below. They demonstrate very close results except at the trench part where the low viscosity in 32^3 case is a bit more blurry.
33x32x32 case:
![SlabSubduction3D2A2Step0](https://user-images.githubusercontent.com/26615840/59958869-02ad2e80-94e0-11e9-9bb1-85237f702d93.png)

32x32x32 case:
![SlabSubduction3D2CStep0](https://user-images.githubusercontent.com/26615840/59958874-16589500-94e0-11e9-8a04-85f8204263db.png)

I will attribute this convergence rate difference to coincidence by now, but will keep an eye on it.

Best regards,
Ting

**Comment by lmoresi** [comment] 2019-06-22 04:24
I don’t understand those numbers … can you clarify “one time faster / slower”


L

On 22 Jun 2019, 1:25 PM +1000, tingyang2004 <notifications@github.com>, wrote:

For the issue that 33x32x32 elements per cpu is one time faster than 32x32x32 elements per cpu. I have checked the log file today. It looks like the pressure solver is one time slower for 32^3 CPUs.
33x32x32 model:

Non linear solver - iteration 14
Linear solver (XQ96L7RB__system-execute)

[1] SROpGenerator_SimpleCoarserLevel: time = 1.83635e-02
Setting schur_pc to "gkgdiag"

SCR Solver Summary:

Multigrid setup: = 0.242 secs
RHS V Solve: = 6.193 secs / 18 its
Pressure Solve: = 212.4 secs / 48 its
Final V Solve: = 5.804 secs / 20 its

Total BSSCR Linear solve time: 236.770290 seconds

Linear solver (XQ96L7RB__system-execute), solution time 2.369147e+02 (secs)
In func SystemLinearEquations_NonLinearExecute: Iteration 14 of 500 - Residual 0.0080322 - Tolerance = 0.01
Non linear solver - Residual 8.03220671e-03; Tolerance 1.0000e-02 - Converged - 4.615428e+03 (secs)

In func SystemLinearEquations_NonLinearExecute: Converged after 14 iterations.
^[[1;35m

Pressure iterations: 48
Velocity iterations: 18 (presolve)
Velocity iterations: 755 (pressure solve)
Velocity iterations: 20 (backsolve)
Velocity iterations: 793 (total solve)

SCR RHS setup time: 1.1543e+01
SCR RHS solve time: 6.1928e+00
Pressure setup time: 6.2304e-03
Pressure solve time: 2.1236e+02
Velocity setup time: 9.5367e-07 (backsolve)
Velocity solve time: 5.8037e+00 (backsolve)
Total solve time : 2.3677e+02

Velocity solution min/max: 0.0000e+00/0.0000e+00
Pressure solution min/max: 0.0000e+00/0.0000e+00

^[[00m
('hgn 12: ', datetime.datetime(2019, 6, 19, 19, 17, 31, 464663))
step = 0; time = 0.00000e+00; time_Myr = 0.00000e+00

32x32x32 model:

Non linear solver - iteration 14
Linear solver (DJ25GQCN__system-execute)

BSSCR -- Block Stokes Schur Compliment Reduction Solver
AUGMENTED LAGRANGIAN K2 METHOD - Penalty = 0.000000

SROpGenerator_SimpleFinestLevel: time = 2.39016e-01
[4] SROpGenerator_SimpleCoarserLevel: time = 4.37264e-02
[3] SROpGenerator_SimpleCoarserLevel: time = 1.78812e-02
[2] SROpGenerator_SimpleCoarserLevel: time = 1.48602e-02
[1] SROpGenerator_SimpleCoarserLevel: time = 1.41797e-02
Setting schur_pc to "gkgdiag"

SCR Solver Summary:

Multigrid setup: = 0.3395 secs
RHS V Solve: = 17.6 secs / 20 its
Pressure Solve: = 640.1 secs / 47 its
Final V Solve: = 16.97 secs / 20 its

Total BSSCR Linear solve time: 679.924037 seconds

Linear solver (DJ25GQCN__system-execute), solution time 6.800786e+02 (secs)
In func SystemLinearEquations_NonLinearExecute: Iteration 14 of 500 - Residual 0.0083099 - Tolerance = 0.01
Non linear solver - Residual 8.30994138e-03; Tolerance 1.0000e-02 - Converged - 9.481746e+03 (secs)

In func SystemLinearEquations_NonLinearExecute: Converged after 14 iterations.
^[[1;35m

Pressure iterations: 47
Velocity iterations: 20 (presolve)
Velocity iterations: 747 (pressure solve)
Velocity iterations: 20 (backsolve)
Velocity iterations: 787 (total solve)

SCR RHS setup time: 4.3717e+00
SCR RHS solve time: 1.7601e+01
Pressure setup time: 6.0389e-03
Pressure solve time: 6.4010e+02
Velocity setup time: 7.1526e-07 (backsolve)
Velocity solve time: 1.6970e+01 (backsolve)
Total solve time : 6.7992e+02

Velocity solution min/max: 0.0000e+00/0.0000e+00
Pressure solution min/max: 0.0000e+00/0.0000e+00

^[[00m
('hgn 12: ', datetime.datetime(2019, 6, 19, 15, 59, 3, 87266))
step = 0; time = 0.00000e+00; time_Myr = 0.00000e+00

I have attached the model viscosity and velocity solution at 0_th step for these two models below. They demonstrate very close results except at the trench part where the low viscosity in 32^3 case is a bit more blurry.
33x32x32 case:
[SlabSubduction3D2A2Step0]<https://user-images.githubusercontent.com/26615840/59958869-02ad2e80-94e0-11e9-9bb1-85237f702d93.png>

32x32x32 case:
[SlabSubduction3D2CStep0]<https://user-images.githubusercontent.com/26615840/59958874-16589500-94e0-11e9-8a04-85f8204263db.png>

I will attribute this convergence rate difference to coincidence by now, but will keep an eye on it.

Best regards,
Ting

**Comment by jmansour** [comment] 2019-06-22 05:11
@lmoresi, I think he means twice as fast for 33x32x32 local resolution run.  Same global resolution.  So

33x32x32:
```bash
  Multigrid setup:        = 0.242 secs
  RHS V Solve:            = 6.193 secs / 18 its
  Pressure Solve:         = 212.4 secs / 48 its
  Final V Solve:          = 5.804 secs / 20 its

  Total BSSCR Linear solve time: 236.770290 seconds
```

32x32x32:
```bash
  Multigrid setup:        = 0.3395 secs
  RHS V Solve:            = 17.6 secs / 20 its
  Pressure Solve:         = 640.1 secs / 47 its
  Final V Solve:          = 16.97 secs / 20 its

  Total BSSCR Linear solve time: 679.924037 seconds
```

@tingyang2004  did you re-run the 32x32x32 run?  If not, can you so that we can see if these timings are repeatable.  They're certainly very peculiar.

**Comment by tingyang2004** [comment] 2019-06-22 05:20
Louis and John,

I think 32x32x32 per core model is slower than 33x32x32 in this specific case, so I guess it is just a coincidence.

32x32x32 per core model (256x96x64 elements in total with 48 cores) takes around 20 min for each linear iteration or around 40 min for each step.
33x32x32 per core model (264x96x64 elements in total with 48 cores) takes around 10 min for each linear iteration or around 20 min for each step.
These results seem repeatable on one server

**Comment by tingyang2004** [comment] 2019-06-22 05:24
Log files for these two models are attached in case you need more information.
[input2A2.out_bk.txt](https://github.com/underworldcode/underworld2/files/3316532/input2A2.out_bk.txt)
[input2C.out_bk.txt](https://github.com/underworldcode/underworld2/files/3316533/input2C.out_bk.txt)

**Comment by jmansour** [comment] 2019-06-22 05:26
Ok, sorry, it's different global resolution (of course). Still very strange.

**Comment by jmansour** [comment] 2019-06-27 07:02
I'll close this ticket as I think it's run its course. Feel free to reopen.

**Closed by jmansour** 2019-06-27 07:02 UTC
