### ISSUE TITLE
UW2.10.1b is 0.6 times slower than UW2.7.1b for the same python script

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#527] opened 2021-02-18 09:22 UTC
Hi all,

I compared the model results and CPU time for UW2.10.1b and UW2.7.1b with a simple visco-plastic slab subduction model. The slab subduction model has a resolution of 400x120 elements and 10 cores are used with a 20 step data-saving frequency (two snapshots of the viscosity field at zero and 200 steps shown below). Although these two UW versions gave extremely close results after running for 200 steps, UW2.10.1b seems 0.6 times lower than UW2.7.1b (see the costed CPU time below). Do you know what may have caused this computational efficiency difference? Please let me know if more information is needed. Thanks a lot.

Best regards,
Ting

![image](https://user-images.githubusercontent.com/26615840/108333984-74d19b80-720c-11eb-89c5-ee68da3a362f.png)
![image](https://user-images.githubusercontent.com/26615840/108334010-7dc26d00-720c-11eb-94b9-1b197b5fa434.png)

![image](https://user-images.githubusercontent.com/26615840/108334804-486a4f00-720d-11eb-8dc9-529ea9e616fa.png)

**Comment by julesghub** [comment] 2021-02-18 23:20
Hi Ting, do you have the `config.cfg` files available for each build? If they achieve similar results I'm guessing it's an installation inefficiency. For version `2.10` the config.cfg is located at /underworld/libUnderworld/

Another idea is that the solver tolerances maybe different in the version (@jmansour did we tweak that at some stage). Do you have the output logs available for each run?

**Comment by tingyang2004** [comment] 2021-02-19 01:21
Thanks, Julian. The comparison was done on my own desktop, and the docker version was used:
docker run -v $PWD:/home/jovyan/ --rm underworldcode/underworld2:2.10.1b mpirun -np 10 python 4ASlabSubduction.py
vs
docker run -v $PWD:/workspace/ --rm underworldcode/underworld2:2.7.1b mpirun -np 10 python 4SlabSubduction.py

Here is the stokes solver setup:
![image](https://user-images.githubusercontent.com/26615840/108443155-3df29880-7293-11eb-949e-c5dd58b05981.png)

The log files seem to suggest that the SCR RHS  setup time in UW2.10.1b is longer than that of UW2.7.1b.
![image](https://user-images.githubusercontent.com/26615840/108443410-ac375b00-7293-11eb-888b-d1b5341e9992.png)

**Comment by tingyang2004** [comment] 2021-02-19 01:24
Here is the setup for the nonlinear part:
solver.solve(nonLinearIterate=True,nonLinearMaxIterations=200,nonLinearTolerance=0.003)

**Comment by tingyang2004** [comment] 2021-03-15 09:09
Is there any progress in solving the convergence efficiency issue?

**Comment by jmansour** [comment] 2021-03-15 23:54
Hi Ting. 

I'm unable to reproduce this. Running the standard slab subduction model against UW 2.7 & 2.10 the timings are relatively close for me.  

Can you post UW 2.7 & 2.10 compatible versions of your script?

**Comment by julesghub** [comment] 2021-03-16 00:07
![image](https://user-images.githubusercontent.com/13825704/111236668-8cebdd80-8647-11eb-9346-40f09f13c4da.png)

I'm able to reproduce this, I'm unclear what it could be. I'm thinking it's the number of integration points (gauss points) used.

**Comment by julesghub** [comment] 2021-03-16 00:11
This was using the `06_SlabSubduction.ipynb` in 2.10.1b and 2.7.1b

**Comment by jmansour** [comment] 2021-03-16 00:13
Which model are you running @julesghub?  Note that in 2.10, the slab subduction model defaults to `mumps` in serial, while in 2.7 it'll use `lu`.

**Comment by julesghub** [comment] 2021-03-16 00:14
Yeah I have seen that but I'm not sure that's significant here, try to test now.

**Comment by tingyang2004** [comment] 2021-03-16 00:25
Thanks, both,

Below are my python scripts for 2.10.1b (4SlabSubduction.py.txt) and 2.7.1b (4ASlabSubduction.py.txt).
[4ASlabSubduction.py.txt](https://github.com/underworldcode/underworld2/files/6145218/4ASlabSubduction.py.txt)
[4SlabSubduction.py.txt](https://github.com/underworldcode/underworld2/files/6145219/4SlabSubduction.py.txt)

I observed this issue both on my own desktop (docker) and on my uni's hpc.

**Comment by julesghub** [comment] 2021-03-16 00:48
Thanks for the models Ting. I'm still investigating what's going on with the example `06_SlabSubduction.ipynb` model. It shows the same behaviour using 2.10 & 2.7 when the model's inner solve methods are set to mumps (like your models), i.e. 2.7 is quicker!

**Comment by lmoresi** [comment] 2021-03-16 02:26
Interesting - the RHS setup time presumably includes building the SCR preconditioner which seems to have suddenly become more expensive but not more effective (iterations have not changed at all). That could be something to do with gauss points v particles as the default preconditioner is built by finding the average viscosity in an element.

**Comment by julesghub** [comment] 2021-03-16 02:57
Using `mumps` on 06_SlabSubduction`. 2.10 on the right, 2.7 on the left. `Pressure solve time` is the difference
![image](https://user-images.githubusercontent.com/13825704/111248987-15c24380-865f-11eb-91d2-ae4d23b37d3e.png)

Interestingly when using `lu` for the inner solver (rather than `mumps`) the timings are very similar.

**Comment by jmansour** [comment] 2021-03-16 03:09
Is it possibly a difference in versions of `mumps`?  Although I'll note that @tingyang2004 observed this issue also on a HPC system, for which I'd assume he was using the same version of `mumps` in both UW2.7 & UW2.10 tests.

**Comment by julesghub** [comment] 2021-03-16 03:25
Potentially, I'm not sure on how to check the version of mumps `petsc` pulls down. 

@tingyang2004 did you use the dockers on HPC or compiled code? If compiled code, do the two versions use consistent petsc/mumps versions?

**Comment by lmoresi** [comment] 2021-03-16 03:43
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1615866217/e0463a85314d353cd65b915287a67da9/5/56e0546f227d5dd9cd487b5bee1a3fe2/0ca5a70446f272d981402b09f313675e/9efab2399c7c560b34de477b9aa0a465/newton.gif]
Except that the time that is much longer is the RHS setup for the SCR (not the RHS solve). Am I right ? That would not be using mumps.

Prof Louis Moresi
***@***.***
(m) +61 4 0333 1413
(us) +1 505 349 4425
www.moresi.info<http://www.moresi.info/>
geo-down-under.geoscience.education<https://geo-down-under.geoscience.education/>
@LouisMoresi<https://twitter.com/LouisMoresi>

On Tue, Mar 16, 2021 at 2:26 PM, Julian Giordani ***@***.***> wrote:

Potentially, I'm not sure on how to check the version of mumps petsc pulls down.

@tingyang2004<https://github.com/tingyang2004> did you use the dockers on HPC or compiled code? If compiled code, do the two versions use consistent petsc/mumps versions?

**Comment by tingyang2004** [comment] 2021-03-16 05:33
I did not check the versions of Petsc I used on HPC, but I assume they are different considering the one year and a half intervals between the installations. How to check the Petsc version conveniently?

**Comment by tingyang2004** [comment] 2021-03-16 05:49
After checking the petsc make.log, the version should be 3.10.5 (uw2.7.1b) and 3.12.1 (uw2.10.1b) respectively.

**Comment by tingyang2004** [comment] 2021-03-22 12:02
It looks to me that the new version of petsc used (3.12.4) has slowed down the Stokes solver. Using different versions of uw but the same version of petsc give similar solver times. So, is there any convenient way to let uw use the older version of petsc in docker?

**Comment by tingyang2004** [comment] 2021-03-22 12:14
Since petsc 3.12.4 is newer, I assume it should be faster than or at least at a similar speed to the older versions (e.g., 3.10.5 here) by deliberately tuning it?

**Comment by jmansour** [comment] 2021-03-22 23:45
I ran some tests using PETSc 3.10.5 against UW 2.7 & 2.10, while the results were identical for `lu`, for `mumps` there were definite differences, with at times the older UW being faster, and at times the new UW.  It's somewhat strange, but does appear to be due to a change in how we use PETSc.

Unfortunately I don't think we can spend more time on this as it's somewhat a niche issue and very difficult to debug.  So if the performance hit is too much, I'd suggest sticking with the older Underworld, or perhaps you might investigate using `superludist`.  This relatively recent publication suggests it does better than `mumps` for their testing configuration:

https://cug.org/proceedings/cug2016_proceedings/includes/files/pap121s2-file1.pdf

**Comment by tingyang2004** [comment] 2021-03-23 00:32
Strange, how much is the MUMPS time difference between UW 2.7 and 2.10?
I will stick to PETSc 3.10.5 on HPC and UW 2.7 in docker at the moment then.

**Comment by jmansour** [comment] 2021-03-23 00:57
It wasn't usually dramatic.. around 20% give or take from memory.

I'd suggest you at least try `superludist`. It should be installed in your Docker, and possibly on your HPC too depending on how PETSc was configured. So you'd simply invoke `solver.set_inner_method("superludist")`.

**Comment by tingyang2004** [comment] 2021-03-23 02:42
Thanks, John. I will check if superludist is faster in the next few weeks.

**Comment by jmansour** [comment] 2021-03-23 03:13
Traditionally people seem to have had better luck with `mumps`, but `superlu_dist` seems to be actively being developed so definitely worth a try. 

Let us know what you find.

**Comment by tingyang2004** [comment] 2021-03-23 05:10
Definitely, will report back when it's done.

**Comment by tingyang2004** [comment] 2021-04-12 02:26
I did not check the details, but changing MUMPS to superludist directly in 2.7.1 shows little influence on the convergence speed. However, changing MUMPS to superludist in 2.10.1 slows the convergence significantly (by around 50 times). So uw2.7.1 with MUMPS looks the best choice at present.

Tests are done in my docker.

**Comment by julesghub** [comment] 2021-07-14 01:37
Closing this ticket. @tingyang2004 thanks for raising this issue. We are planning on implementing performance metrics because of this kind of issue. Cheers!

**Closed by julesghub** 2021-07-14 01:37 UTC
