### ISSUE TITLE
Seg Fault while using MUMPS solver in parallel on Raijin-nci

### ISSUE THREAD

**Issue by gthyagi** [underworldcode/underworld2#368] opened 2019-04-09 12:06 UTC
Hi,
I installed underworld2 regionalMesh branch on Raijin with python-3.6.7 and petsc-3.9.4. While running example script (i.e., 05_Rayleigh_Taylor) in parallel on Raijin with MUMPS solver shows following error 
"""
Error running Underworld - Signal 11 'SIGSEGV' (Segmentation Fault).
This is probably caused by an illegal access of memory.
We recommend running the code in a debugger to work out where the problem is (e.g. 'gdb')
and also to contact the developers.
"""
Attaching modified script [05_Rayleigh_Taylor-Copy1.txt](https://github.com/underworldcode/underworld2/files/3058804/05_Rayleigh_Taylor-Copy1.txt)

Note: Same script runs without any errors on single node in Raijin.

**Comment by julesghub** [comment] 2019-04-11 00:08
@gthyagi - I can reproduce the error of mumps in parallel. Unfortunately I don't have a fix for it yet.
Can you not use mumps for now? i.e. use the default 'mg' solver.
I'll keep the ticket open and continue to debug mumps and 'regionalMesh' on raijin.

Also I made some modifications for the raijin build instructions for py3 here - obviously not stable! It's a work in progress so any input would be welcome. https://github.com/underworldcode/underworld2/blob/04bdfbc908cf05324a79e574d92310c74729c353/docs/install_guides/nci_raijin.sh

**Comment by jmansour** [comment] 2019-06-27 07:29
@julesghub, is this still an issue?

**Comment by julesghub** [comment] 2019-06-27 23:09
i'll test today. 
@gthyagi have you got anymore information on this ticket?

**Comment by gthyagi** [comment] 2019-06-28 03:18
@julesghub, I don't have further information on this issue. Currently I am not using mg and running models with default solver.

**Comment by julesghub** [comment] 2019-07-03 06:08
Confirming this is still an active issue. `mumps` causes a seg. fault in parallel whereas `mg` doesn't. I'm unclear as to why. Will test more in the coming week.

**Comment by rbeucher** [comment] 2019-08-07 03:05
@julesghub 
I am having issues with MUMPS on raijin. I am still using 2.7. MUMPS does not crash but result is complete garbage.

**Comment by julesghub** [comment] 2019-08-07 04:55
hmm? Garbage results. The error I found was a crash. I recall it happened the 2nd time the stokes solver was called in parallel.

**Comment by rcarluccio** [comment] 2019-08-28 02:40
Hi everyone,

any updates on this? I'm also experiencing the same issue with petsc 3.7.4, which was working until august the 5th.

**Comment by rbeucher** [comment] 2019-08-28 02:44
Yes. You should update to 2.8 with petsc 3.9.4

**Comment by jmansour** [comment] 2019-08-28 02:48
Wait, so is `mumps` working in parallel on Raijin?  There seems to be some confusion about this.  Is petsc 3.9.4 the magic ingredient?

**Comment by rbeucher** [comment] 2019-08-28 02:54
Yes mumps works in parallel on raijin after following the new install instructions for 2.8
I have models running with 12 - 24 CPUs...
Now I don't know if petsc 3.9.4 is the magic ingredient.

**Comment by rcarluccio** [comment] 2019-08-28 03:01
it seems like a lot of magic is happening here.

**Comment by gthyagi** [comment] 2019-08-28 03:32
> Yes mumps works in parallel on raijin after following the new install instructions for 2.8
> I have models running with 12 - 24 CPUs...
> Now I don't know if petsc 3.9.4 is the magic ingredient.

My observation of this petsc magic:
I am using petsc 3.9.4 still mumps is not working for me.
Note: using regional mesh branch and requested 32 cpus.

**Comment by rcarluccio** [comment] 2019-08-28 03:34
is there some back magic? @john mansour <john.mansour@monash.edu>

**Comment by gthyagi** [comment] 2019-08-28 03:56
@julesghub , here are some updates on regional branch solver status.
Out of 4 solver (fgmres, mg, mumps, slud), two solver fgmres and mg are working fine in both annulus and 3D spherical models. Slud is working properly in annulus models and throwing error (seg fault) in 3D models after first time step. Mumps is not working in either of my models. I installed the latest version of regional mesh branch with your nci installation instructions.
slud : super lu distributed

**Comment by jmansour** [comment] 2019-08-28 04:03
Yeah definitely some sort of voodoo going on here.  
@gthyagi which instructions did you use?  The `regionalMesh` version or the `latest` version?

**Comment by gthyagi** [comment] 2019-08-28 04:18
@jmansour , I am using regionalMesh version.
Here is the link for instructions https://github.com/underworldcode/underworld2/issues/407#issuecomment-521275353

**Comment by jmansour** [comment] 2019-08-28 21:59
But that link is for the latest version.  So are you using regionalMesh:
https://github.com/underworldcode/underworld2/blob/regionalMesh/docs/install_guides/nci_raijin.sh

or latest:
https://github.com/underworldcode/underworld2/blob/v2.8.0b/docs/install_guides/nci_raijin.sh

I see a few potential problems with the `regionalMesh` version.  There's a potential conflict of OpenMPI versions being used:

mpi4py : OpenMPI 3.1.3
petsc:  OpenMPI 3.1.2
h5py: OpenMPI 3.0.1

The last in the particular could cause issues, given it's a bigger version increment. 

The `latest` version of the install guide looks pretty consistent to me, using correct versions of OpenMPI for petsc, and then rebuilding mpi4py & h5py.

**Comment by rbeucher** [comment] 2020-06-16 00:34
Closing this now that Raijin Has been decommissioned.

**Closed by rbeucher** 2020-06-16 00:34 UTC
