### ISSUE TITLE
Sudden Change in Temperature Field

### ISSUE THREAD

**Issue by lsli0116** [underworldcode/underworld2#557] opened 2021-07-11 14:09 UTC
Hi all,

I am ready to modeling the double subduction with underworld, and find after several steps (about 100 steps), the temperature of this model will suddenly change and then after several steps, the temperature will be back to normal. But in the several steps, the motion state of the subduction will be deeply affected (because of the temperature-dependent viscosity), and it's really strange and I can't find the reasons. Could anyone provide me some useful suggestions? 

This is the initial state of temperature field, and it's symmetrical:
![figTemp-0000](https://user-images.githubusercontent.com/34978045/125198201-81c25a80-e293-11eb-9eb5-5bb99e85a8e4.png)

And after 90 steps, it's symmetrical as usual:
![figTemp-0090](https://user-images.githubusercontent.com/34978045/125198328-11680900-e294-11eb-9546-6e4ec48d1aa6.png)

But between the 100-120 steps, the temperature will be suddenly changed, and I don't know where the error comes from.

![figTemp-0100](https://user-images.githubusercontent.com/34978045/125198395-44aa9800-e294-11eb-8f66-d9f708fc9733.png)
![figTemp-0110](https://user-images.githubusercontent.com/34978045/125198396-45432e80-e294-11eb-86e1-e2e9afaf667a.png)
![figTemp-0120](https://user-images.githubusercontent.com/34978045/125198397-45dbc500-e294-11eb-8ea1-4932ef003515.png)

And after 160th step, the temperature will be back to normal state, but you can see a little asymmetrical state between left and right (a little slow in the right side)
![figTemp-0160](https://user-images.githubusercontent.com/34978045/125198465-8dfae780-e294-11eb-9a56-397bc85af14c.png)

**Comment by julesghub** [comment] 2021-07-11 23:28
There appears high (max) temperature zones on the upper edges of the slabs at t=100-120. The colour bar max is set to red and the colour bar has a dynamic range. 
So the max temp dominates the image. Thus the mantle goes from red -> to olive green when the high zone appears, but it seems the mantle temperature is consistent.

I believe the high temperature zones are caused by advection oscillations in the energy solver. This happens when sharp gradients are being advected. The thermal boundary between the slab and mantle looks like a sharp gradient. 
Here are a few general things you could do to decrease the gradients and improve the advection algorithm.
1) Diffuse the temperature gradients of the model.
2) Use more elements to get better numerical resolution.
3) Try smaller timesteps.

Which advection diffusion algorithm are you using? SLCN or SUPG?

**Comment by lsli0116** [comment] 2021-07-12 06:34
> There appears high (max) temperature zones on the upper edges of the slabs at t=100-120. The colour bar max is set to red and the colour bar has a dynamic range.
> So the max temp dominates the image. Thus the mantle goes from red -> to olive green when the high zone appears, but it seems the mantle temperature is consistent.
> 
> I believe the high temperature zones are caused by advection oscillations in the energy solver. This happens when sharp gradients are being advected. The thermal boundary between the slab and mantle looks like a sharp gradient.
> Here are a few general things you could do to decrease the gradients and improve the advection algorithm.
> 
> 1. Diffuse the temperature gradients of the model.
> 2. Use more elements to get better numerical resolution.
> 3. Try smaller timesteps.
> 
> Which advection diffusion algorithm are you using? SLCN or SUPG?

Thanks for your suggestions, I prefer to diffuse the temperature gradient of the model, do you mean I need to diffuse the temperature field in each step? Because I diffuse the temperature field in the first step but the problem still exist.

And I use the SUPG with temperaturedotfield. Is SLCN method better?

**Comment by julesghub** [comment] 2021-08-16 07:09
SLCN is better for advection dominated problem but unfortunately the implementation is only available for non-deformed meshes. So please continue with SUPG.
The issue as you point out is the erroneous temperatures. The temperature oscillations can be mitigated as I mentioned previously but to prevent the errors feeding into the temperature dependent viscosity another idea comes to mind.

Clip the temperature field to be in the range 0-1 to ensure completely unrealistic temperature values don't feed into the viscosity condition. This should help the "run away" viscosity feedback too. i.e.
`temperatureField.data[:] = np.where(temperatureField.data>1., temperatureField.data, 1)`

**Comment by rbeucher** [comment] 2022-05-24 23:27
Closing this as we have not heard from the OP in a while.

**Closed by rbeucher** 2022-05-24 23:27 UTC
